/*
 * ShapePanel.java
 *
 * Created on April 9, 2008, 11:51 AM
 */

package javaapplication4;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;

//import org.openide.util.Exceptions;

/**
 * @author  Administrador
 */
public class ShapePanel extends javax.swing.JPanel {
    public DemoGraphScene scene ;
    public BufferedImage fondo;
    public JLabel label2 ;
            
    /** Creates new form ShapePanel */
    public ShapePanel() {

            System.out.println("ba");
            scene = new DemoGraphScene();
            System.out.println("scenconstend");
            initComponents();
            //Load Image
            try{
                 fondo = ImageIO.read(new File("/media/WOXTER/SLAM/Programas/JavaApplication4/src/javaapplication4/kkk0002.tif"));
                 label2= new JLabel(new ImageIcon(fondo));
                 label2.setBounds(0,0,fondo.getWidth(),fondo.getHeight());
                 
                 jLayeredPane1.add(label2,new Integer(JLayeredPane.DEFAULT_LAYER-1) );
                
            }catch (IOException e )
            {
               System.out.println( e.getMessage());
            }
            
            Icon image = new ImageIcon("QCam-icon.gif");
            JLabel label = new JLabel(image);
            JComponent sceneView = scene.createView ();
            //jLayeredPane1.add(sceneView,JLayeredPane.DEFAULT_LAYER);
            jScrollPane1.setOpaque(false);
            jScrollPane1.getViewport().setOpaque(false);
            sceneView.setOpaque(false);
            scene.setOpaque(false);
            //jScrollPane1.getViewport().add(label);
            jScrollPane1.setViewportView(sceneView);            
            
            System.out.println("bb");
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();

        jButton1.setText(org.openide.util.NbBundle.getMessage(ShapePanel.class, "ShapePanel.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication4/play_icon.gif"))); // NOI18N
        jButton2.setText(org.openide.util.NbBundle.getMessage(ShapePanel.class, "ShapePanel.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane1.setBounds(0, 0, 610, 420);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 417, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jButton2)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        scene.Add();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
         System.out.println("play");
        
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
