/*
 * test3.java
 *
 * Created on April 14, 2008, 5:25 PM
 */

package javaapplication4;

/**
 *
 * @author  Administrador
 */
public class test3 extends java.awt.Frame {
    
    /** Creates new form test3 */
    public test3() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabel1.setText(org.openide.util.NbBundle.getMessage(test3.class, "test3.jLabel1.text")); // NOI18N
        add(jLabel1, java.awt.BorderLayout.CENTER);

        jLabel2.setText(org.openide.util.NbBundle.getMessage(test3.class, "test3.jLabel2.text")); // NOI18N
        add(jLabel2, java.awt.BorderLayout.NORTH);

        jLabel3.setText(org.openide.util.NbBundle.getMessage(test3.class, "test3.jLabel3.text")); // NOI18N
        add(jLabel3, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test3().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
    
}
