3DSlam: CTracker_surf Class Reference
CTracker_surf Class Reference
Seeded Up Robust Features.
#include <tracker_surf.h>
Public Member Functions
CTracker_surf ()
~CTracker_surf ()
void Match (IplImage *f)
int Init (IplImage *img, int **keys, CvMat **points)
void Descriptor (IplImage *img, CvPoint *point, int s, int *key)
int getFeatDim ()
Private Attributes
IplImage * img
IplImage * fImg
CSurf surf
int levels
Detailed Description
Seeded Up Robust Features.
Author:
Jorge Artieda
Definition at line 18 of file tracker_surf.h.
Constructor & Destructor Documentation
CTracker_surf::CTracker_surf ()
Definition at line 5 of file tracker_surf.cpp.
References CTracker::feat, levels, and CTracker::storage.
CTracker_surf::~CTracker_surf ()
Definition at line 15 of file tracker_surf.cpp.
Member Function Documentation
void CTracker_surf::Match (IplImage * f) [virtual]
FIXME Esto tiene que estar relacionado con un valor mas claro del surf
Implements CTracker.
Definition at line 24 of file tracker_surf.cpp.
References CMap::bbdd, CSurf::descriptor(), CTracker::feat, CSurf::find_features(), CSurf::img, levels, CSurf::nearest_neighbor_2(), CSurf::orientation(), CTracker::pMap, st_inited, st_no_view, surf, and CMap::visible.
int CTracker_surf::Init (IplImage * img, int ** keys, CvMat ** points) [virtual]
Implements CTracker.
Definition at line 121 of file tracker_surf.cpp.
References CSurf::descriptor(), CTracker::feat, CSurf::find_features(), CSurf::img, levels, CSurf::orientation(), and surf.
void CTracker_surf::Descriptor (IplImage * img, CvPoint * point, int s, int * key) [virtual]
Obtiene el descriptor asociado a un punto con una escala detrminada
Implements CTracker.
Definition at line 175 of file tracker_surf.cpp.
References CSurf::descriptor(), CSurf::img, CSurf::orientation(), and surf.
int CTracker_surf::getFeatDim () [virtual]
Devuelve el tamaño en bytes del vector de características
Implements CTracker.
Definition at line 20 of file tracker_surf.cpp.
Member Data Documentation
IplImage* CTracker_surf::img [private]
Definition at line 32 of file tracker_surf.h.
IplImage* CTracker_surf::fImg [private]
Definition at line 33 of file tracker_surf.h.
CSurf CTracker_surf::surf [private]
Definition at line 35 of file tracker_surf.h.
Referenced by Descriptor(), Init(), and Match().
int CTracker_surf::levels [private]
Definition at line 36 of file tracker_surf.h.
Referenced by CTracker_surf(), Init(), and Match().
The documentation for this class was generated from the following files:
D:/SLAM/Programas/slamsvn/src/tracker_surf.h
D:/SLAM/Programas/slamsvn/src/tracker_surf.cpp