3DSlam: javaapplication4::test2 Class Reference
javaapplication4::test2 Class Reference
Public Member Functions
test2 ()
Static Public Member Functions
static void main (String args[])
Private Member Functions
void initComponents ()
Private Attributes
javax.swing.JLabel jLabel1
javax.swing.JLabel jLabel2
Detailed Description
Author:
Administrador
Definition at line 13 of file test2.java.
Constructor & Destructor Documentation
javaapplication4::test2::test2 () [inline]
Creates new form test2
Definition at line 16 of file test2.java.
References initComponents().
Referenced by main().
Member Function Documentation
void javaapplication4::test2::initComponents () [inline, private]
This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 26 of file test2.java.
References jLabel1, and jLabel2.
Referenced by test2().
static void javaapplication4::test2::main (String args[]) [inline, static]
Parameters:
args the command line arguments
Definition at line 64 of file test2.java.
References test2().
Member Data Documentation
javax.swing.JLabel javaapplication4::test2::jLabel1 [private]
Definition at line 73 of file test2.java.
Referenced by initComponents().
javax.swing.JLabel javaapplication4::test2::jLabel2 [private]
Definition at line 74 of file test2.java.
Referenced by initComponents().
The documentation for this class was generated from the following file:
D:/SLAM/Programas/slamsvn/JavaApplication4/src/javaapplication4/test2.java