3DSlam: CModel Class Reference
CModel Class Reference
Clase abstracta para implementar modelos de movimiento de cámaras.
#include <model.h>
Public Member Functions
CModel ()
virtual ~CModel ()
CvMat * getTransitionMatrix ()
int getStateNum ()
CvMat * getProcessNoiseCov ()
CvMat * getMeasurementMatrix ()
CvMat * getMeasurementNoiseCov ()
int getMeasurementNum ()
CvMat * getInputMatrix ()
CvMat * getInputCov ()
int getInputNum ()
void setModelCam (CModelCam *p)
enlaza la clase kalman con la clase model cam
void setDataCam (CDataCam *p)
enlaza la clase kalman con la clase data cam
void setMap (CMap *p)
enlaza kalman con mapa
virtual CvMat * getMeasurementVector ()=0
Protected Attributes
int StateNum
CvMat * TransitionMatrix
CvMat * ProcessNoiseCov
CvMat * MeasurementMatrix
CvMat * MeasurementNoiseCov
int MeasurementNum
CvMat * InputMatrix
CvMat * InputCov
int InputNum
CvMat * MeasurementVector
CModelCam * pModelCam
puntero a modelo de la camara para proyectar y jacobiano
CDataCam * pDataCam
puntero a datos de la camara
CMap * pMap
puntero a datos del mapa
Detailed Description
Clase abstracta para implementar modelos de movimiento de cámaras.
Author:
Jorge Artieda
Definition at line 15 of file model.h.
Constructor & Destructor Documentation
CModel::CModel ()
Definition at line 3 of file model.cpp.
CModel::~CModel () [virtual]
Definition at line 6 of file model.cpp.
Member Function Documentation
CvMat * CModel::getTransitionMatrix ()
Definition at line 10 of file model.cpp.
References TransitionMatrix.
Referenced by CParticleFilter::setModel(), and CKalman::setModel().
int CModel::getStateNum ()
Definition at line 30 of file model.cpp.
References StateNum.
Referenced by CParticleFilter::Correct(), CKalman::Correct(), CKalman::Correct_FAST(), CKalman::Predict_FAST(), CParticleFilter::ProjectParticle(), CParticleFilter::setModel(), CKalman::setModel(), CKalman::UpdateJacob(), CParticleFilter::UpdateMatrixSize(), and CKalman::UpdateMatrixSize().
CvMat * CModel::getProcessNoiseCov ()
Definition at line 14 of file model.cpp.
References ProcessNoiseCov.
Referenced by CParticleFilter::setModel(), and CKalman::setModel().
CvMat * CModel::getMeasurementMatrix ()
Definition at line 18 of file model.cpp.
References MeasurementMatrix.
Referenced by CKalman::setModel(), CKalman::UpdateJacob(), and CKalman::UpdateMatrixSize().
CvMat * CModel::getMeasurementNoiseCov ()
Definition at line 22 of file model.cpp.
References MeasurementNoiseCov.
Referenced by CKalman::setModel(), and CKalman::UpdateMatrixSize().
int CModel::getMeasurementNum ()
Definition at line 26 of file model.cpp.
References MeasurementNum.
Referenced by CKalman::Correct(), CKalman::Correct_FAST(), param_init(), CParticleFilter::setModel(), CKalman::setModel(), CKalman::Test(), CKalman::UpdateJacob(), CParticleFilter::UpdateMatrixSize(), and CKalman::UpdateMatrixSize().
CvMat * CModel::getInputMatrix ()
Definition at line 34 of file model.cpp.
References InputMatrix.
CvMat * CModel::getInputCov ()
Definition at line 38 of file model.cpp.
References InputCov.
int CModel::getInputNum ()
Definition at line 42 of file model.cpp.
References InputNum.
Referenced by CKalman::setModel().
void CModel::setModelCam (CModelCam * p)
enlaza la clase kalman con la clase model cam
Definition at line 46 of file model.cpp.
References pModelCam.
void CModel::setDataCam (CDataCam * p)
enlaza la clase kalman con la clase data cam
Definition at line 50 of file model.cpp.
References pDataCam.
void CModel::setMap (CMap * p)
enlaza kalman con mapa
Definition at line 54 of file model.cpp.
References pMap.
virtual CvMat* CModel::getMeasurementVector () [pure virtual]
Implemented in CFreeCam.
Referenced by CKalman::Correct(), and CKalman::Correct_FAST().
Member Data Documentation
int CModel::StateNum [protected]
Definition at line 34 of file model.h.
Referenced by CFreeCam::CFreeCam(), and getStateNum().
CvMat* CModel::TransitionMatrix [protected]
Definition at line 35 of file model.h.
Referenced by CFreeCam::CFreeCam(), getTransitionMatrix(), and CFreeCam::~CFreeCam().
CvMat* CModel::ProcessNoiseCov [protected]
Definition at line 36 of file model.h.
Referenced by CFreeCam::CFreeCam(), getProcessNoiseCov(), and CFreeCam::~CFreeCam().
CvMat* CModel::MeasurementMatrix [protected]
Definition at line 37 of file model.h.
Referenced by getMeasurementMatrix().
CvMat* CModel::MeasurementNoiseCov [protected]
Definition at line 38 of file model.h.
Referenced by getMeasurementNoiseCov().
int CModel::MeasurementNum [protected]
Definition at line 39 of file model.h.
Referenced by CFreeCam::CFreeCam(), and getMeasurementNum().
CvMat* CModel::InputMatrix [protected]
Definition at line 40 of file model.h.
Referenced by getInputMatrix().
CvMat* CModel::InputCov [protected]
Definition at line 41 of file model.h.
Referenced by getInputCov().
int CModel::InputNum [protected]
Definition at line 42 of file model.h.
Referenced by CFreeCam::CFreeCam(), and getInputNum().
CvMat* CModel::MeasurementVector [protected]
Definition at line 43 of file model.h.
Referenced by CFreeCam::CFreeCam(), CFreeCam::getMeasurementVector(), and CFreeCam::~CFreeCam().
CModelCam* CModel::pModelCam [protected]
puntero a modelo de la camara para proyectar y jacobiano
Definition at line 44 of file model.h.
Referenced by setModelCam().
CDataCam* CModel::pDataCam [protected]
puntero a datos de la camara
Definition at line 45 of file model.h.
Referenced by setDataCam().
CMap* CModel::pMap [protected]
puntero a datos del mapa
Definition at line 46 of file model.h.
Referenced by setMap().
The documentation for this class was generated from the following files:
D:/SLAM/Programas/slamsvn/src/model.h
D:/SLAM/Programas/slamsvn/src/model.cpp