3DSlam: CUpdater Class Reference
CUpdater Class Reference
#include <updater.h>
Public Member Functions
CUpdater (CMap *pMap_, CDataCam *pDataCam_)
CUpdater ()
void setMap (CMap *p)
void setDataCam (CDataCam *p)
void setModelCam (CModelCam *p)
void setTracker (CTracker *p)
void TestRANSAC ()
void randsample (vector< point > *data, int n, vector< point > *maybeinliners)
double fits (point p, param model)
double fit (param *model, vector< point > points)
void ranasac (vector< point > orig_data, int k, int n, double t, int d)
~CUpdater ()
int update ()
int busca_esquinas (IplImage *f, CvPoint *pts, int count)
int busca_posibles_para_anadir (IplImage *f, IplImage *f2, int faltan)
int Add (IplImage *f, IplImage *f2)
int AddByHand (IplImage *f)
int remove ()
int rematch ()
Public Attributes
param maybemodel
param bettermodel
param bestfit
CMap * pMap
CDataCam * pDataCam
CModelCam * pModelCam
CTracker * pTracker
int border
int num_feat_min
int num_feat_max
double point_sep
double calidad_min_punto
double depth
Detailed Description
Definition at line 23 of file updater.h.
Constructor & Destructor Documentation
CUpdater::CUpdater (CMap * pMap_, CDataCam * pDataCam_)
constructor
Parameters:
pMap puntero al mapa que se actualizará
pDataCam puntero a los parámetros de la cámara
CUIDADO ESTE CONSTRUCTOR NO SE USA
Definition at line 25 of file updater.cpp.
References border, calidad_min_punto, depth, num_feat_max, num_feat_min, pDataCam, pMap, and point_sep.
CUpdater::CUpdater ()
constructor por defecto establece un borde de 30 y un número de características de 30
Definition at line 47 of file updater.cpp.
References border, calidad_min_punto, depth, num_feat_max, num_feat_min, and point_sep.
CUpdater::~CUpdater ()
Definition at line 39 of file updater.cpp.
Member Function Documentation
void CUpdater::setMap (CMap * p)
Definition at line 302 of file updater.cpp.
References pMap.
Referenced by conect().
void CUpdater::setDataCam (CDataCam * p)
Definition at line 306 of file updater.cpp.
References pDataCam.
Referenced by conect().
void CUpdater::setModelCam (CModelCam * p)
Definition at line 310 of file updater.cpp.
References pModelCam.
Referenced by conect().
void CUpdater::setTracker (CTracker * p)
Definition at line 315 of file updater.cpp.
References pTracker.
Referenced by conect().
void CUpdater::TestRANSAC ()
Definition at line 276 of file updater.cpp.
References CMap::bbdd, point::ground, point::ID, point::img, pMap, ranasac(), and st_inited.
void CUpdater::randsample (vector< point > * data, int n, vector< point > * maybeinliners)
Definition at line 58 of file updater.cpp.
Referenced by ranasac().
double CUpdater::fits (point p, param model)
Definition at line 166 of file updater.cpp.
References point::ground, point::img, param::px, and param::py.
Referenced by ranasac().
double CUpdater::fit (param * model, vector< point > points)
Definition at line 191 of file updater.cpp.
References param::px, and param::py.
Referenced by ranasac().
void CUpdater::ranasac (vector< point > orig_data, int k, int n, double t, int d)
Definition at line 85 of file updater.cpp.
References CMap::bbdd, bestfit, bettermodel, fit(), fits(), maybemodel, pMap, param::px, param::py, randsample(), st_inited, st_no_view, and CMap::visible.
Referenced by TestRANSAC().
int CUpdater::update ()
Definition at line 329 of file updater.cpp.
References CMap::bbdd, CModelCam::cvInverseParam(), depth, pDataCam, pMap, pModelCam, st_empty, st_inited, and CDataCam::translation.
Referenced by main().
int CUpdater::busca_esquinas (IplImage * f, CvPoint * pts, int count)
funcion obsoleta
Definition at line 610 of file updater.cpp.
int CUpdater::busca_posibles_para_anadir (IplImage * f, IplImage * f2, int faltan)
llama a pTracker para obtener una lista de puntos que se pueden usar
los puntos se anaden si cumplen una serie de condiciones
Parameters:
f frame sobre el que buscar los puntos
faltan numero de puntos que se necesitan anadir
Returns:
el numero de puntos anadidos
En el caso de tracker file FIXME
Definition at line 377 of file updater.cpp.
References CMap::add_key(), CMap::bbdd, border, calidad_min_punto, CDataCam::frame_height, CDataCam::frame_width, CTracker::getFeatDim(), CTracker::Init(), pDataCam, pMap, point_sep, pTracker, and st_inited.
Referenced by Add().
int CUpdater::Add (IplImage * f, IplImage * f2)
se anaden puntos al mapa
Parameters:
f frame sobre el que buscar puntos
f2 frame anterior tiene que coincidir
Definition at line 521 of file updater.cpp.
References CMap::bbdd, busca_posibles_para_anadir(), num_feat_max, num_feat_min, pMap, st_inited, st_no_view, and CMap::visible.
Referenced by init_ptos(), and main().
int CUpdater::AddByHand (IplImage * f)
añadir un punto manual
Definition at line 552 of file updater.cpp.
References CMap::add_key(), CTracker::Descriptor(), CTracker::feat, CTracker::getFeatDim(), num_feat_min, on_mouse(), pMap, pTracker, and CMap::visible.
int CUpdater::remove ()
establece condiciones en la que los puntos se deben borrar FIXME es un poco redundante con la funcion match de la clase tracker y debe ser modificada.
FIXME En el casod de que el punto se deje de ver antes de inicializar quiero borrarlo.
Definition at line 636 of file updater.cpp.
References CMap::bbdd, border, CDataCam::frame_height, CDataCam::frame_width, pDataCam, pMap, st_inited, st_no_view, and CMap::visible.
Referenced by main().
int CUpdater::rematch ()
TODO hace falta implementar esto
Definition at line 676 of file updater.cpp.
Member Data Documentation
param CUpdater::maybemodel
Definition at line 36 of file updater.h.
Referenced by ranasac().
param CUpdater::bettermodel
Definition at line 37 of file updater.h.
Referenced by ranasac().
param CUpdater::bestfit
Definition at line 38 of file updater.h.
Referenced by ranasac().
CMap* CUpdater::pMap
Definition at line 41 of file updater.h.
Referenced by Add(), AddByHand(), busca_posibles_para_anadir(), CUpdater(), ranasac(), remove(), setMap(), TestRANSAC(), and update().
CDataCam* CUpdater::pDataCam
Definition at line 42 of file updater.h.
Referenced by busca_posibles_para_anadir(), CUpdater(), remove(), setDataCam(), and update().
CModelCam* CUpdater::pModelCam
Definition at line 43 of file updater.h.
Referenced by setModelCam(), and update().
CTracker* CUpdater::pTracker
Definition at line 44 of file updater.h.
Referenced by AddByHand(), busca_posibles_para_anadir(), and setTracker().
int CUpdater::border
Definition at line 54 of file updater.h.
Referenced by busca_posibles_para_anadir(), CUpdater(), and remove().
int CUpdater::num_feat_min
Definition at line 55 of file updater.h.
Referenced by Add(), AddByHand(), and CUpdater().
int CUpdater::num_feat_max
Definition at line 56 of file updater.h.
Referenced by Add(), and CUpdater().
double CUpdater::point_sep
Definition at line 57 of file updater.h.
Referenced by busca_posibles_para_anadir(), and CUpdater().
double CUpdater::calidad_min_punto
Definition at line 58 of file updater.h.
Referenced by busca_posibles_para_anadir(), and CUpdater().
double CUpdater::depth
Definition at line 59 of file updater.h.
Referenced by CUpdater(), and update().
The documentation for this class was generated from the following files:
D:/SLAM/Programas/slamsvn/src/updater.h
D:/SLAM/Programas/slamsvn/src/updater.cpp