3DSlam: CTracker Class Reference
CTracker Class Reference
Clase abstracta para implementar seguidores.
#include <tracker.h>
Public Member Functions
CTracker ()
virtual ~CTracker ()
void setDataCam (CDataCam *p)
void setModelCam (CModelCam *p)
void setMap (CMap *p)
virtual void Match (IplImage *f)=0
virtual int Init (IplImage *img, int **keys, CvMat **points)=0
virtual void Descriptor (IplImage *img, CvPoint *point, int s, int *key)=0
virtual int getFeatDim ()=0
Public Attributes
CvSeq * feat
CvMemStorage * storage
Protected Attributes
CDataCam * pDataCam
CModelCam * pModelCam
CMap * pMap
Detailed Description
Clase abstracta para implementar seguidores.
Author:
Jorge Artieda
Definition at line 15 of file tracker.h.
Constructor & Destructor Documentation
CTracker::CTracker ()
Definition at line 5 of file tracker.cpp.
CTracker::~CTracker () [virtual]
Definition at line 10 of file tracker.cpp.
Member Function Documentation
void CTracker::setDataCam (CDataCam * p)
Definition at line 15 of file tracker.cpp.
References pDataCam.
Referenced by conect(), and param_init().
void CTracker::setModelCam (CModelCam * p)
Definition at line 19 of file tracker.cpp.
References pModelCam.
void CTracker::setMap (CMap * p)
Definition at line 24 of file tracker.cpp.
References pMap.
Referenced by param_init().
virtual void CTracker::Match (IplImage * f) [pure virtual]
Implemented in CTracker_harris, CTracker_surf, and CTrackerFile.
Referenced by main().
virtual int CTracker::Init (IplImage * img, int ** keys, CvMat ** points) [pure virtual]
Implemented in CTracker_harris, CTracker_surf, and CTrackerFile.
Referenced by CUpdater::busca_posibles_para_anadir().
virtual void CTracker::Descriptor (IplImage * img, CvPoint * point, int s, int * key) [pure virtual]
Implemented in CTracker_harris, CTracker_surf, and CTrackerFile.
Referenced by CUpdater::AddByHand().
virtual int CTracker::getFeatDim () [pure virtual]
Implemented in CTracker_harris, CTracker_surf, and CTrackerFile.
Referenced by CUpdater::AddByHand(), and CUpdater::busca_posibles_para_anadir().
Member Data Documentation
CvSeq* CTracker::feat
Definition at line 29 of file tracker.h.
Referenced by CUpdater::AddByHand(), CTracker_surf::CTracker_surf(), CTracker_surf::Init(), and CTracker_surf::Match().
CvMemStorage* CTracker::storage
Definition at line 30 of file tracker.h.
Referenced by CTracker_surf::CTracker_surf().
CDataCam* CTracker::pDataCam [protected]
Definition at line 32 of file tracker.h.
Referenced by setDataCam().
CModelCam* CTracker::pModelCam [protected]
Definition at line 33 of file tracker.h.
Referenced by setModelCam().
CMap* CTracker::pMap [protected]
Definition at line 34 of file tracker.h.
Referenced by CTrackerFile::Match(), CTracker_surf::Match(), CTracker_harris::Match(), and setMap().
The documentation for this class was generated from the following files:
D:/SLAM/Programas/slamsvn/src/tracker.h
D:/SLAM/Programas/slamsvn/src/tracker.cpp