3DSlam: CTrackerFile Class Reference
CTrackerFile Class Reference
#include <trackerfile.h>
Public Member Functions
CTrackerFile ()
virtual ~CTrackerFile ()
virtual void Match (IplImage *f)
virtual int Init (IplImage *img, int **keys, CvMat **points)
virtual void Descriptor (IplImage *img, CvPoint *point, int s, int *key)
virtual int getFeatDim ()
Protected Attributes
FILE * f
int frame
bool first
Detailed Description
Definition at line 6 of file trackerfile.h.
Constructor & Destructor Documentation
CTrackerFile::CTrackerFile ()
Definition at line 6 of file trackerfile.cpp.
CTrackerFile::~CTrackerFile () [virtual]
Definition at line 11 of file trackerfile.cpp.
Member Function Documentation
void CTrackerFile::Match (IplImage * f) [virtual]
add point
Implements CTracker.
Definition at line 16 of file trackerfile.cpp.
References CMap::add_key(), CMap::bbdd, f, FORIGEN, frame, getFeatDim(), CTracker::pMap, st_inited, st_no_view, and CMap::visible.
int CTrackerFile::Init (IplImage * img, int ** keys, CvMat ** points) [virtual]
Implements CTracker.
Definition at line 75 of file trackerfile.cpp.
References f, first, FORIGEN, and frame.
void CTrackerFile::Descriptor (IplImage * img, CvPoint * point, int s, int * key) [virtual]
Implements CTracker.
Definition at line 101 of file trackerfile.cpp.
int CTrackerFile::getFeatDim () [virtual]
realmente no almaceno ningun punto.
Implements CTracker.
Definition at line 104 of file trackerfile.cpp.
Referenced by Match().
Member Data Documentation
FILE* CTrackerFile::f [protected]
Definition at line 17 of file trackerfile.h.
Referenced by Init(), and Match().
int CTrackerFile::frame [protected]
Definition at line 18 of file trackerfile.h.
Referenced by Init(), and Match().
bool CTrackerFile::first [protected]
Definition at line 19 of file trackerfile.h.
Referenced by Init().
The documentation for this class was generated from the following files:
D:/SLAM/Programas/slamsvn/src/trackerfile.h
D:/SLAM/Programas/slamsvn/src/trackerfile.cpp