3DSlam: javaapplication4::ShapePanel Class Reference
javaapplication4::ShapePanel Class Reference
Public Member Functions
ShapePanel ()
Public Attributes
DemoGraphScene scene
BufferedImage fondo
JLabel label2
Private Member Functions
void initComponents ()
void jButton1ActionPerformed (java.awt.event.ActionEvent evt)
void jButton2ActionPerformed (java.awt.event.ActionEvent evt)
Private Attributes
javax.swing.JButton jButton1
javax.swing.JButton jButton2
javax.swing.JLayeredPane jLayeredPane1
javax.swing.JScrollPane jScrollPane1
Detailed Description
Author:
Administrador
Definition at line 24 of file ShapePanel.java.
Constructor & Destructor Documentation
javaapplication4::ShapePanel::ShapePanel () [inline]
Creates new form ShapePanel
Definition at line 30 of file ShapePanel.java.
References fondo, initComponents(), jLayeredPane1, jScrollPane1, label2, and scene.
Member Function Documentation
void javaapplication4::ShapePanel::initComponents () [inline, private]
This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 70 of file ShapePanel.java.
References jButton1, jButton1ActionPerformed(), jButton2, jButton2ActionPerformed(), jLayeredPane1, and jScrollPane1.
Referenced by ShapePanel().
void javaapplication4::ShapePanel::jButton1ActionPerformed (java.awt.event.ActionEvent evt) [inline, private]
Definition at line 128 of file ShapePanel.java.
References javaapplication4::DemoGraphScene::Add(), and scene.
Referenced by initComponents().
void javaapplication4::ShapePanel::jButton2ActionPerformed (java.awt.event.ActionEvent evt) [inline, private]
Definition at line 133 of file ShapePanel.java.
Referenced by initComponents().
Member Data Documentation
DemoGraphScene javaapplication4::ShapePanel::scene
Definition at line 25 of file ShapePanel.java.
Referenced by jButton1ActionPerformed(), and ShapePanel().
BufferedImage javaapplication4::ShapePanel::fondo
Definition at line 26 of file ShapePanel.java.
Referenced by javaapplication4::start::setImage(), and ShapePanel().
JLabel javaapplication4::ShapePanel::label2
Definition at line 27 of file ShapePanel.java.
Referenced by javaapplication4::start::setImage(), and ShapePanel().
javax.swing.JButton javaapplication4::ShapePanel::jButton1 [private]
Definition at line 141 of file ShapePanel.java.
Referenced by initComponents().
javax.swing.JButton javaapplication4::ShapePanel::jButton2 [private]
Definition at line 142 of file ShapePanel.java.
Referenced by initComponents().
javax.swing.JLayeredPane javaapplication4::ShapePanel::jLayeredPane1 [private]
Definition at line 143 of file ShapePanel.java.
Referenced by initComponents(), and ShapePanel().
javax.swing.JScrollPane javaapplication4::ShapePanel::jScrollPane1 [private]
Definition at line 144 of file ShapePanel.java.
Referenced by initComponents(), and ShapePanel().
The documentation for this class was generated from the following file:
D:/SLAM/Programas/slamsvn/JavaApplication4/src/javaapplication4/ShapePanel.java