3DSlam: CModelCam Class Reference
CModelCam Class Reference
Ecuaciones del modelo de cámara pin-hole.
#include <modelcam.h>
Public Member Functions
CModelCam ()
virtual ~CModelCam ()
void ProjectPoints ()
void cvProjectPoints3 (const CvMat *obj_points, const CvMat *r_vec, const CvMat *t_vec, const CvMat *A, const CvMat *dist_coeffs, CvMat *img_points, CvMat *dpdr, CvMat *dpdt, CvMat *dpdf, CvMat *dpdc, CvMat *dpdk, CvMat *dpdw)
funcion de proyeccion de puntos de opencv
void cvProject_1_pto (CvMat *obj, CvMat *img, CvMat *dpdr, CvMat *dpdt, CvMat *dpdw)
void cvInverseParam (CvMat **h, CvPoint pto)
void setDataCam (CDataCam *p)
void setMap (CMap *p)
void getJInit (CvMat *Jpos, CvMat *Jpix, CvPoint pto)
Private Attributes
CDataCam * pDataCam
CMap * pMap
Detailed Description
Ecuaciones del modelo de cámara pin-hole.
Author:
Jorge Artieda
Definition at line 13 of file modelcam.h.
Constructor & Destructor Documentation
CModelCam::CModelCam ()
Definition at line 5 of file modelcam.cpp.
CModelCam::~CModelCam () [virtual]
Definition at line 10 of file modelcam.cpp.
Member Function Documentation
void CModelCam::ProjectPoints ()
proyecta los puntos que existen en pMap
rellena los puntos y las derivadas
En esta función se aplican las derivadas respecto del las variables de parametrización inversa.
FIXME solo se debería proyectar sobre los puntos iniciados
Definition at line 21 of file modelcam.cpp.
References CMap::bbdd, cvProject_1_pto(), and pMap.
Referenced by CParticleFilter::Correct(), init_ptos(), main(), and CKalman::UpdateJacob().
void CModelCam::cvProjectPoints3 (const CvMat * obj_points, const CvMat * r_vec, const CvMat * t_vec, const CvMat * A, const CvMat * dist_coeffs, CvMat * img_points, CvMat * dpdr, CvMat * dpdt, CvMat * dpdf, CvMat * dpdc, CvMat * dpdk, CvMat * dpdw)
funcion de proyeccion de puntos de opencv
la funcion de proyeccion es la misma que opencv pero ampliada para devolver la derivada de los puntos respecto de los puntos
Definition at line 202 of file modelcam.cpp.
Referenced by cvProject_1_pto().
void CModelCam::cvProject_1_pto (CvMat * nobj, CvMat * nimg, CvMat * dpdr, CvMat * dpdt, CvMat * dpdw)
funcion para proyectar un punto y conseguir su Jacobiana
Parameters:
nobj puntos 3D
nimg punto proyectado de salida
dpdr
dpdt
dpdw
Definition at line 94 of file modelcam.cpp.
References CDataCam::calibration, cvProjectPoints3(), CDataCam::distortion, pDataCam, CDataCam::rotation, and CDataCam::translation.
Referenced by CDataOut::Disp_out(), CParticleFilter::ProjectParticle(), and ProjectPoints().
void CModelCam::cvInverseParam (CvMat ** h, CvPoint pto)
Definition at line 177 of file modelcam.cpp.
References CDataCam::calibration, pDataCam, and CDataCam::rotMat.
Referenced by init_ptos(), and CUpdater::update().
void CModelCam::setDataCam (CDataCam * p)
Definition at line 167 of file modelcam.cpp.
References pDataCam.
Referenced by conect().
void CModelCam::setMap (CMap * p)
Definition at line 172 of file modelcam.cpp.
References pMap.
Referenced by conect().
void CModelCam::getJInit (CvMat * Jpos, CvMat * Jpix, CvPoint pto)
cálculo de la derivada de la inicialización de los parámetros respecto de la posción y de los puntos
se calcula por incrementos finitos
Definition at line 609 of file modelcam.cpp.
References CDataCam::calibration, pDataCam, CDataCam::rotation, CDataCam::rotMat, and CDataCam::translation.
Member Data Documentation
CDataCam* CModelCam::pDataCam [private]
Definition at line 40 of file modelcam.h.
Referenced by cvInverseParam(), cvProject_1_pto(), getJInit(), and setDataCam().
CMap* CModelCam::pMap [private]
Definition at line 41 of file modelcam.h.
Referenced by ProjectPoints(), and setMap().
The documentation for this class was generated from the following files:
D:/SLAM/Programas/slamsvn/src/modelcam.h
D:/SLAM/Programas/slamsvn/src/modelcam.cpp