3DSlam: javaapplication4::test3 Class Reference
javaapplication4::test3 Class Reference
Public Member Functions
test3 ()
Static Public Member Functions
static void main (String args[])
Private Member Functions
void initComponents ()
void exitForm (java.awt.event.WindowEvent evt)
Private Attributes
javax.swing.JLabel jLabel1
javax.swing.JLabel jLabel2
javax.swing.JLabel jLabel3
Detailed Description
Author:
Administrador
Definition at line 13 of file test3.java.
Constructor & Destructor Documentation
javaapplication4::test3::test3 () [inline]
Creates new form test3
Definition at line 16 of file test3.java.
References initComponents().
Referenced by main().
Member Function Documentation
void javaapplication4::test3::initComponents () [inline, private]
This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 26 of file test3.java.
References exitForm(), jLabel1, jLabel2, and jLabel3.
Referenced by test3().
void javaapplication4::test3::exitForm (java.awt.event.WindowEvent evt) [inline, private]
Exit the Application
Definition at line 51 of file test3.java.
Referenced by initComponents().
static void javaapplication4::test3::main (String args[]) [inline, static]
Parameters:
args the command line arguments
Definition at line 58 of file test3.java.
References test3().
Member Data Documentation
javax.swing.JLabel javaapplication4::test3::jLabel1 [private]
Definition at line 68 of file test3.java.
Referenced by initComponents().
javax.swing.JLabel javaapplication4::test3::jLabel2 [private]
Definition at line 69 of file test3.java.
Referenced by initComponents().
javax.swing.JLabel javaapplication4::test3::jLabel3 [private]
Definition at line 70 of file test3.java.
Referenced by initComponents().
The documentation for this class was generated from the following file:
D:/SLAM/Programas/slamsvn/JavaApplication4/src/javaapplication4/test3.java