3DSlam: ???_WOSD functions.
???_WOSD functions.
[Create or Update the XMLNode structure]
Functions
static XMLNode XMLNode::createXMLTopNode_WOSD (XMLSTR lpszName, char isDeclaration=FALSE)
Create the top node of an XMLNode structure.
XMLNode XMLNode::addChild_WOSD (XMLSTR lpszName, char isDeclaration=FALSE, XMLElementPosition pos=-1)
Add a new child node.
XMLAttribute * XMLNode::addAttribute_WOSD (XMLSTR lpszName, XMLSTR lpszValue)
Add a new attribute.
XMLCSTR XMLNode::addText_WOSD (XMLSTR lpszValue, XMLElementPosition pos=-1)
Add a new text content.
XMLClear * XMLNode::addClear_WOSD (XMLSTR lpszValue, XMLCSTR lpszOpen=NULL, XMLCSTR lpszClose=NULL, XMLElementPosition pos=-1)
Add a new clear Tag.
XMLCSTR XMLNode::updateName_WOSD (XMLSTR lpszName)
change node's name
XMLAttribute * XMLNode::updateAttribute_WOSD (XMLAttribute *newAttribute, XMLAttribute *oldAttribute)
if the attribute to update is missing, a new one will be added
XMLAttribute * XMLNode::updateAttribute_WOSD (XMLSTR lpszNewValue, XMLSTR lpszNewName=NULL, int i=0)
if the attribute to update is missing, a new one will be added
XMLAttribute * XMLNode::updateAttribute_WOSD (XMLSTR lpszNewValue, XMLSTR lpszNewName, XMLCSTR lpszOldName)
set lpszNewName=NULL if you don't want to change the name of the attribute if the attribute to update is missing, a new one will be added
XMLCSTR XMLNode::updateText_WOSD (XMLSTR lpszNewValue, int i=0)
if the text to update is missing, a new one will be added
XMLCSTR XMLNode::updateText_WOSD (XMLSTR lpszNewValue, XMLCSTR lpszOldValue)
if the text to update is missing, a new one will be added
XMLClear * XMLNode::updateClear_WOSD (XMLSTR lpszNewContent, int i=0)
if the clearTag to update is missing, a new one will be added
XMLClear * XMLNode::updateClear_WOSD (XMLClear *newP, XMLClear *oldP)
if the clearTag to update is missing, a new one will be added
XMLClear * XMLNode::updateClear_WOSD (XMLSTR lpszNewValue, XMLCSTR lpszOldValue)
if the clearTag to update is missing, a new one will be added
Detailed Description
The strings given as parameters for the "add" and "update" methods that have a name with the postfix "_WOSD" (that means "WithOut String Duplication")(for example "addText_WOSD") will be free'd by the XMLNode class. For example, it means that this is incorrect:
     xNode.addText_WOSD("foo");
     xNode.updateAttribute_WOSD("#newcolor" ,NULL,"color");
In opposition, this is correct:
     xNode.addText("foo");
     xNode.addText_WOSD(stringDup("foo"));
     xNode.updateAttribute("#newcolor" ,NULL,"color");
     xNode.updateAttribute_WOSD(stringDup("#newcolor"),NULL,"color");
Typically, you will never do:
     char *b=(char*)malloc(...);
     xNode.addText(b);
     free(b);
... but rather:
     char *b=(char*)malloc(...);
     xNode.addText_WOSD(b);
('free(b)' is performed by the XMLNode class)
Function Documentation
XMLAttribute * XMLNode::addAttribute_WOSD (XMLSTR lpszName, XMLSTR lpszValue) [inherited]
Add a new attribute.
Definition at line 2532 of file xmlParser.cpp.
References XMLNode::addAttribute_priv().
Referenced by XMLNode::updateAttribute_WOSD().
XMLNode XMLNode::addChild_WOSD (XMLSTR lpszName, char isDeclaration = FALSE, XMLElementPosition pos = -1) [inherited]
Add a new child node.
Definition at line 2528 of file xmlParser.cpp.
References XMLNode::addChild_priv().
XMLClear * XMLNode::addClear_WOSD (XMLSTR lpszValue, XMLCSTR lpszOpen = NULL, XMLCSTR lpszClose = NULL, XMLElementPosition pos = -1) [inherited]
Add a new clear Tag.
Definition at line 2540 of file xmlParser.cpp.
References XMLNode::addClear_priv().
Referenced by XMLNode::updateClear_WOSD().
XMLCSTR XMLNode::addText_WOSD (XMLSTR lpszValue, XMLElementPosition pos = -1) [inherited]
Add a new text content.
Definition at line 2536 of file xmlParser.cpp.
References XMLNode::addText_priv().
Referenced by XMLNode::updateText_WOSD().
XMLNode XMLNode::createXMLTopNode_WOSD (XMLSTR lpszName, char isDeclaration = FALSE) [static, inherited]
Create the top node of an XMLNode structure.
Definition at line 998 of file xmlParser.cpp.
References XMLNode::XMLNode().
XMLAttribute * XMLNode::updateAttribute_WOSD (XMLSTR lpszNewValue, XMLSTR lpszNewName, XMLCSTR lpszOldName) [inherited]
set lpszNewName=NULL if you don't want to change the name of the attribute if the attribute to update is missing, a new one will be added
Definition at line 2249 of file xmlParser.cpp.
References XMLNode::addAttribute_WOSD(), XMLNode::getAttribute(), stringDup(), and XMLNode::updateAttribute_WOSD().
XMLAttribute * XMLNode::updateAttribute_WOSD (XMLSTR lpszNewValue, XMLSTR lpszNewName = NULL, int i = 0) [inherited]
if the attribute to update is missing, a new one will be added
Definition at line 2228 of file xmlParser.cpp.
References XMLNode::addAttribute_WOSD(), XMLAttribute::lpszName, and XMLAttribute::lpszValue.
XMLAttribute * XMLNode::updateAttribute_WOSD (XMLAttribute * newAttribute, XMLAttribute * oldAttribute) [inherited]
if the attribute to update is missing, a new one will be added
Definition at line 2243 of file xmlParser.cpp.
References XMLNode::addAttribute_WOSD(), XMLAttribute::lpszName, XMLAttribute::lpszValue, and XMLSTR.
Referenced by XMLNode::updateAttribute(), and XMLNode::updateAttribute_WOSD().
XMLClear * XMLNode::updateClear_WOSD (XMLSTR lpszNewValue, XMLCSTR lpszOldValue) [inherited]
if the clearTag to update is missing, a new one will be added
Definition at line 2332 of file xmlParser.cpp.
References XMLNode::addClear_WOSD(), XMLNode::indexClear(), and XMLNode::updateClear_WOSD().
XMLClear * XMLNode::updateClear_WOSD (XMLClear * newP, XMLClear * oldP) [inherited]
if the clearTag to update is missing, a new one will be added
Definition at line 2340 of file xmlParser.cpp.
References XMLClear::lpszValue, XMLNode::updateClear_WOSD(), and XMLSTR.
XMLClear * XMLNode::updateClear_WOSD (XMLSTR lpszNewContent, int i = 0) [inherited]
if the clearTag to update is missing, a new one will be added
Definition at line 2323 of file xmlParser.cpp.
References XMLNode::addClear_WOSD(), and XMLClear::lpszValue.
Referenced by XMLNode::updateClear(), and XMLNode::updateClear_WOSD().
XMLCSTR XMLNode::updateName_WOSD (XMLSTR lpszName) [inherited]
change node's name
Definition at line 965 of file xmlParser.cpp.
Referenced by XMLNode::updateName(), and XMLNode::XMLNode().
XMLCSTR XMLNode::updateText_WOSD (XMLSTR lpszNewValue, XMLCSTR lpszOldValue) [inherited]
if the text to update is missing, a new one will be added
Definition at line 2292 of file xmlParser.cpp.
References XMLNode::addText_WOSD(), XMLNode::indexText(), and XMLNode::updateText_WOSD().
XMLCSTR XMLNode::updateText_WOSD (XMLSTR lpszNewValue, int i = 0) [inherited]
if the text to update is missing, a new one will be added
Definition at line 2283 of file xmlParser.cpp.
References XMLNode::addText_WOSD(), and XMLCSTR.
Referenced by XMLNode::updateText(), and XMLNode::updateText_WOSD().