3DSlam: Position helper functions (use in conjunction with the update&add functions
Position helper functions (use in conjunction with the update&add functions
[Create or Update the XMLNode structure]
Functions
XMLElementPosition XMLNode::positionOfText (int i=0) const
XMLElementPosition XMLNode::positionOfText (XMLCSTR lpszValue) const
XMLElementPosition XMLNode::positionOfClear (int i=0) const
XMLElementPosition XMLNode::positionOfClear (XMLCSTR lpszValue) const
XMLElementPosition XMLNode::positionOfClear (XMLClear *a) const
XMLElementPosition XMLNode::positionOfChildNode (int i=0) const
XMLElementPosition XMLNode::positionOfChildNode (XMLNode x) const
XMLElementPosition XMLNode::positionOfChildNode (XMLCSTR name, int i=0) const
return the position of the ith childNode with the specified name if (name==NULL) return the position of the ith childNode
Detailed Description
These are some useful functions when you want to insert a childNode, a text or a XMLClearTag in the middle (at a specified position) of a XMLNode tree already constructed. The value returned by these methods is to be used as last parameter (parameter 'pos') of addChild, addText or addClear.
Function Documentation
XMLElementPosition XMLNode::positionOfChildNode (XMLCSTR name, int i = 0) const [inherited]
return the position of the ith childNode with the specified name if (name==NULL) return the position of the ith childNode
Definition at line 2407 of file xmlParser.cpp.
References eNodeChild, XMLNode::findPosition(), XMLNode::getChildNode(), and XMLNode::positionOfChildNode().
XMLElementPosition XMLNode::positionOfChildNode (XMLNode x) const [inherited]
Definition at line 2398 of file xmlParser.cpp.
References XMLNode::d, eNodeChild, XMLNode::findPosition(), and XMLNode::XMLNodeDataTag::pChild.
XMLElementPosition XMLNode::positionOfChildNode (int i = 0) const [inherited]
Definition at line 2394 of file xmlParser.cpp.
References eNodeChild, and XMLNode::findPosition().
Referenced by XMLNode::positionOfChildNode().
XMLElementPosition XMLNode::positionOfClear (XMLClear * a) const [inherited]
Definition at line 2397 of file xmlParser.cpp.
References XMLClear::lpszValue, and XMLNode::positionOfClear().
XMLElementPosition XMLNode::positionOfClear (XMLCSTR lpszValue) const [inherited]
Definition at line 2396 of file xmlParser.cpp.
References XMLNode::indexClear(), and XMLNode::positionOfClear().
XMLElementPosition XMLNode::positionOfClear (int i = 0) const [inherited]
Definition at line 2393 of file xmlParser.cpp.
References eNodeClear, and XMLNode::findPosition().
Referenced by XMLNode::positionOfClear().
XMLElementPosition XMLNode::positionOfText (XMLCSTR lpszValue) const [inherited]
Definition at line 2395 of file xmlParser.cpp.
References XMLNode::indexText(), and XMLNode::positionOfText().
XMLElementPosition XMLNode::positionOfText (int i = 0) const [inherited]
Definition at line 2392 of file xmlParser.cpp.
References eNodeText, and XMLNode::findPosition().
Referenced by XMLNode::positionOfText().