3DSlam: Navigate the XMLNode structure
Navigate the XMLNode structure
Functions
XMLCSTR XMLNode::getName () const
name of the node
XMLCSTR XMLNode::getText (int i=0) const
return ith text field
int XMLNode::nText () const
nbr of text field
XMLNode XMLNode::getParentNode () const
return the parent node
XMLNode XMLNode::getChildNode (int i=0) const
return ith child node
XMLNode XMLNode::getChildNode (XMLCSTR name, int i) const
return ith child node with specific name (return an empty node if failing). If i==-1, this returns the last XMLNode with the given name.
XMLNode XMLNode::getChildNode (XMLCSTR name, int *i=NULL) const
return next child node with specific name (return an empty node if failing)
XMLNode XMLNode::getChildNodeWithAttribute (XMLCSTR tagName, XMLCSTR attributeName, XMLCSTR attributeValue=NULL, int *i=NULL) const
return child node with specific name/attribute (return an empty node if failing)
int XMLNode::nChildNode (XMLCSTR name) const
return the number of child node with specific name
int XMLNode::nChildNode () const
nbr of child node
XMLAttribute XMLNode::getAttribute (int i=0) const
return ith attribute
XMLCSTR XMLNode::getAttributeName (int i=0) const
return ith attribute name
XMLCSTR XMLNode::getAttributeValue (int i=0) const
return ith attribute value
char XMLNode::isAttributeSet (XMLCSTR name) const
test if an attribute with a specific name is given
XMLCSTR XMLNode::getAttribute (XMLCSTR name, int i) const
return ith attribute content with specific name (return a NULL if failing)
XMLCSTR XMLNode::getAttribute (XMLCSTR name, int *i=NULL) const
return next attribute content with specific name (return a NULL if failing)
int XMLNode::nAttribute () const
nbr of attribute
XMLClear XMLNode::getClear (int i=0) const
return ith clear field (comments)
int XMLNode::nClear () const
nbr of clear field
XMLNodeContents XMLNode::enumContents (XMLElementPosition i) const
enumerate all the different contents (attribute,child,text, clear) of the current XMLNode. The order is reflecting the order of the original file/string. NOTE: 0 <= i < nElement();
int XMLNode::nElement () const
nbr of different contents for current node
char XMLNode::isEmpty () const
is this node Empty?
char XMLNode::isDeclaration () const
is this node a declaration <? .... ?>
XMLNode XMLNode::deepCopy () const
deep copy (duplicate/clone) a XMLNode
static XMLNode XMLNode::emptyNode ()
return XMLNode::emptyXMLNode;
Function Documentation
XMLNode XMLNode::deepCopy () const [inherited]
deep copy (duplicate/clone) a XMLNode
Definition at line 2135 of file xmlParser.cpp.
References XMLNode::d, XMLNode::deepCopy(), XMLClear::lpszCloseTag, XMLAttribute::lpszName, XMLClear::lpszOpenTag, XMLClear::lpszValue, XMLAttribute::lpszValue, XMLNode::XMLNodeDataTag::nAttribute, XMLNode::XMLNodeDataTag::nChild, XMLNode::XMLNodeDataTag::nClear, XMLNode::XMLNodeDataTag::nText, XMLNode::XMLNodeDataTag::pAttribute, XMLNode::XMLNodeDataTag::pChild, XMLNode::XMLNodeDataTag::pClear, XMLNode::XMLNodeDataTag::pOrder, XMLNode::XMLNodeDataTag::pParent, XMLNode::XMLNodeDataTag::pText, stringDup(), and XMLCSTR.
Referenced by XMLNode::deepCopy().
XMLNode XMLNode::emptyNode () [static, inherited]
return XMLNode::emptyXMLNode;
Definition at line 2524 of file xmlParser.cpp.
XMLNodeContents XMLNode::enumContents (XMLElementPosition i) const [inherited]
enumerate all the different contents (attribute,child,text, clear) of the current XMLNode. The order is reflecting the order of the original file/string. NOTE: 0 <= i < nElement();
Definition at line 2486 of file xmlParser.cpp.
References XMLNodeContents::attrib, XMLNodeContents::child, XMLNodeContents::clear, eNodeAttribute, eNodeChild, eNodeClear, eNodeNULL, eNodeText, XMLNodeContents::etype, XMLNode::nAttribute(), and XMLNodeContents::text.
XMLCSTR XMLNode::getAttribute (XMLCSTR name, int * i = NULL) const [inherited]
return next attribute content with specific name (return a NULL if failing)
Definition at line 2444 of file xmlParser.cpp.
References XMLAttribute::lpszName, XMLAttribute::lpszValue, and xstricmp().
XMLCSTR XMLNode::getAttribute (XMLCSTR name, int i) const [inherited]
return ith attribute content with specific name (return a NULL if failing)
Definition at line 2478 of file xmlParser.cpp.
References XMLNode::getAttribute().
XMLAttribute XMLNode::getAttribute (int i = 0) const [inherited]
return ith attribute
Definition at line 2516 of file xmlParser.cpp.
References XMLNode::emptyXMLAttribute.
Referenced by XMLNode::deleteAttribute(), XMLNode::getAttribute(), XMLNode::getChildNodeWithAttribute(), and XMLNode::updateAttribute_WOSD().
XMLCSTR XMLNode::getAttributeName (int i = 0) const [inherited]
return ith attribute name
Definition at line 2517 of file xmlParser.cpp.
XMLCSTR XMLNode::getAttributeValue (int i = 0) const [inherited]
return ith attribute value
Definition at line 2518 of file xmlParser.cpp.
XMLNode XMLNode::getChildNode (XMLCSTR name, int * i = NULL) const [inherited]
return next child node with specific name (return an empty node if failing)
Definition at line 2359 of file xmlParser.cpp.
References XMLNode::d, XMLNode::emptyXMLNode, XMLNode::XMLNodeDataTag::lpszName, and xstricmp().
XMLNode XMLNode::getChildNode (XMLCSTR name, int i) const [inherited]
return ith child node with specific name (return an empty node if failing). If i==-1, this returns the last XMLNode with the given name.
Definition at line 2377 of file xmlParser.cpp.
References XMLNode::emptyXMLNode, XMLNode::getChildNode(), and xstricmp().
XMLNode XMLNode::getChildNode (int i = 0) const [inherited]
return ith child node
Definition at line 2520 of file xmlParser.cpp.
References XMLNode::emptyXMLNode.
Referenced by XMLNode::getChildNode(), XMLNode::getChildNodeWithAttribute(), main(), XMLNode::parseString(), XMLNode::positionOfChildNode(), and XMLNode::writeToFile().
XMLNode XMLNode::getChildNodeWithAttribute (XMLCSTR tagName, XMLCSTR attributeName, XMLCSTR attributeValue = NULL, int * i = NULL) const [inherited]
return child node with specific name/attribute (return an empty node if failing)
Definition at line 2415 of file xmlParser.cpp.
References XMLNode::emptyXMLNode, XMLNode::getAttribute(), XMLNode::getChildNode(), XMLNode::isAttributeSet(), XMLNode::isEmpty(), XMLCSTR, and xstricmp().
XMLClear XMLNode::getClear (int i = 0) const [inherited]
return ith clear field (comments)
Definition at line 2515 of file xmlParser.cpp.
References XMLNode::emptyXMLClear.
XMLCSTR XMLNode::getName () const [inherited]
name of the node
Definition at line 2509 of file xmlParser.cpp.
Referenced by XMLNode::parseString().
XMLNode XMLNode::getParentNode () const [inherited]
return the parent node
Definition at line 2521 of file xmlParser.cpp.
References XMLNode::emptyXMLNode, and XMLNode::XMLNode().
XMLCSTR XMLNode::getText (int i = 0) const [inherited]
return ith text field
Definition at line 2519 of file xmlParser.cpp.
Referenced by main().
char XMLNode::isAttributeSet (XMLCSTR name) const [inherited]
test if an attribute with a specific name is given
Definition at line 2462 of file xmlParser.cpp.
References FALSE, XMLAttribute::lpszName, TRUE, and xstricmp().
Referenced by XMLNode::getChildNodeWithAttribute().
char XMLNode::isDeclaration () const [inherited]
is this node a declaration <? .... ?>
Definition at line 2522 of file xmlParser.cpp.
Referenced by XMLNode::parseString(), and XMLNode::writeToFile().
char XMLNode::isEmpty () const [inherited]
is this node Empty?
Definition at line 2523 of file xmlParser.cpp.
Referenced by XMLNode::getChildNodeWithAttribute(), and XMLNode::ParseXMLElement().
int XMLNode::nAttribute () const [inherited]
nbr of attribute
Definition at line 2512 of file xmlParser.cpp.
Referenced by XMLNode::enumContents().
int XMLNode::nChildNode () const [inherited]
nbr of child node
Definition at line 2511 of file xmlParser.cpp.
int XMLNode::nChildNode (XMLCSTR name) const [inherited]
return the number of child node with specific name
Definition at line 2346 of file xmlParser.cpp.
References XMLNode::d, XMLNode::XMLNodeDataTag::lpszName, and xstricmp().
Referenced by XMLNode::parseString().
int XMLNode::nClear () const [inherited]
nbr of clear field
Definition at line 2513 of file xmlParser.cpp.
int XMLNode::nElement () const [inherited]
nbr of different contents for current node
Definition at line 2514 of file xmlParser.cpp.
Referenced by XMLNode::parseString().
int XMLNode::nText () const [inherited]
nbr of text field
Definition at line 2510 of file xmlParser.cpp.