3DSlam: Creating from scratch a XMLNode structure
Creating from scratch a XMLNode structure
[Create or Update the XMLNode structure]
Functions
static XMLNode XMLNode::createXMLTopNode (XMLCSTR lpszName, char isDeclaration=FALSE)
Create the top node of an XMLNode structure.
XMLNode XMLNode::addChild (XMLCSTR lpszName, char isDeclaration=FALSE, XMLElementPosition pos=-1)
Add a new child node.
XMLNode XMLNode::addChild (XMLNode nodeToAdd, XMLElementPosition pos=-1)
If the "nodeToAdd" has some parents, it will be detached from it's parents before being attached to the current XMLNode.
XMLAttribute * XMLNode::addAttribute (XMLCSTR lpszName, XMLCSTR lpszValuev)
Add a new attribute.
XMLCSTR XMLNode::addText (XMLCSTR lpszValue, XMLElementPosition pos=-1)
Add a new text content.
XMLClear * XMLNode::addClear (XMLCSTR lpszValue, XMLCSTR lpszOpen=NULL, XMLCSTR lpszClose=NULL, XMLElementPosition pos=-1)
Function Documentation
XMLAttribute * XMLNode::addAttribute (XMLCSTR lpszName, XMLCSTR lpszValuev) [inherited]
Add a new attribute.
Definition at line 2530 of file xmlParser.cpp.
References XMLNode::addAttribute_priv(), and stringDup().
XMLNode XMLNode::addChild (XMLNode nodeToAdd, XMLElementPosition pos = -1) [inherited]
If the "nodeToAdd" has some parents, it will be detached from it's parents before being attached to the current XMLNode.
Definition at line 2185 of file xmlParser.cpp.
References XMLNode::addChild(), XMLNode::addToOrder(), XMLNode::d, XMLNode::detachFromParent(), eNodeChild, XMLNode::XMLNodeDataTag::lpszName, XMLNode::XMLNodeDataTag::nChild, XMLNode::XMLNodeDataTag::pChild, XMLNode::XMLNodeDataTag::pParent, and XMLNode::XMLNodeDataTag::ref_count.
XMLNode XMLNode::addChild (XMLCSTR lpszName, char isDeclaration = FALSE, XMLElementPosition pos = -1) [inherited]
Add a new child node.
Definition at line 2526 of file xmlParser.cpp.
References XMLNode::addChild_priv(), and stringDup().
Referenced by XMLNode::addChild().
XMLClear * XMLNode::addClear (XMLCSTR lpszValue, XMLCSTR lpszOpen = NULL, XMLCSTR lpszClose = NULL, XMLElementPosition pos = -1) [inherited]
Add a new clear tag
Parameters:
lpszOpen default value "<![CDATA["
lpszClose default value "]]>"
Definition at line 2538 of file xmlParser.cpp.
References XMLNode::addClear_priv(), and stringDup().
XMLCSTR XMLNode::addText (XMLCSTR lpszValue, XMLElementPosition pos = -1) [inherited]
Add a new text content.
Definition at line 2534 of file xmlParser.cpp.
References XMLNode::addText_priv(), and stringDup().
XMLNode XMLNode::createXMLTopNode (XMLCSTR lpszName, char isDeclaration = FALSE) [static, inherited]
Create the top node of an XMLNode structure.
Definition at line 999 of file xmlParser.cpp.
References stringDup(), and XMLNode::XMLNode().