3DSlam: Deleting Nodes or Attributes
Deleting Nodes or Attributes
[Create or Update the XMLNode structure]
Functions
void XMLNode::deleteNodeContent ()
The "deleteNodeContent" function forces the deletion of the content of this XMLNode and the subtree.
void XMLNode::deleteAttribute (int i=0)
Delete the ith attribute of the current XMLNode.
void XMLNode::deleteAttribute (XMLCSTR lpszName)
Delete the attribute with the given name (the "strcmp" function is used to find the right attribute).
void XMLNode::deleteAttribute (XMLAttribute *anAttribute)
Delete the attribute with the name "anAttribute->lpszName" (the "strcmp" function is used to find the right attribute).
void XMLNode::deleteText (int i=0)
Delete the Ith text content of the current XMLNode.
void XMLNode::deleteText (XMLCSTR lpszValue)
Delete the text content "lpszValue" inside the current XMLNode (direct "pointer-to-pointer" comparison is used to find the right text).
void XMLNode::deleteClear (int i=0)
Delete the Ith clear tag inside the current XMLNode.
void XMLNode::deleteClear (XMLCSTR lpszValue)
Delete the clear tag "lpszValue" inside the current XMLNode (direct "pointer-to-pointer" comparison is used to find the clear tag).
void XMLNode::deleteClear (XMLClear *p)
Delete the clear tag "p" inside the current XMLNode (direct "pointer-to-pointer" comparison on the lpszName of the clear tag is used to find the clear tag).
Detailed Description
Some deletion functions:
Function Documentation
void XMLNode::deleteAttribute (XMLAttribute * anAttribute) [inherited]
Delete the attribute with the name "anAttribute->lpszName" (the "strcmp" function is used to find the right attribute).
Definition at line 2220 of file xmlParser.cpp.
References XMLNode::deleteAttribute(), and XMLAttribute::lpszName.
void XMLNode::deleteAttribute (XMLCSTR lpszName) [inherited]
Delete the attribute with the given name (the "strcmp" function is used to find the right attribute).
Definition at line 2221 of file xmlParser.cpp.
References XMLNode::deleteAttribute(), and XMLNode::getAttribute().
void XMLNode::deleteAttribute (int i = 0) [inherited]
Delete the ith attribute of the current XMLNode.
Definition at line 2210 of file xmlParser.cpp.
References XMLAttribute::lpszName, and XMLAttribute::lpszValue.
Referenced by XMLNode::deleteAttribute().
void XMLNode::deleteClear (XMLClear * p) [inherited]
Delete the clear tag "p" inside the current XMLNode (direct "pointer-to-pointer" comparison on the lpszName of the clear tag is used to find the clear tag).
Definition at line 2321 of file xmlParser.cpp.
References XMLNode::deleteClear(), and XMLClear::lpszValue.
void XMLNode::deleteClear (XMLCSTR lpszValue) [inherited]
Delete the clear tag "lpszValue" inside the current XMLNode (direct "pointer-to-pointer" comparison is used to find the clear tag).
Definition at line 2320 of file xmlParser.cpp.
References XMLNode::deleteClear(), and XMLNode::indexClear().
void XMLNode::deleteClear (int i = 0) [inherited]
Delete the Ith clear tag inside the current XMLNode.
Definition at line 2300 of file xmlParser.cpp.
References eNodeClear, XMLClear::lpszValue, and XMLNode::removeOrderElement().
Referenced by XMLNode::deleteClear(), and XMLNode::maybeAddTxT().
void XMLNode::deleteNodeContent () [inherited]
The "deleteNodeContent" function forces the deletion of the content of this XMLNode and the subtree.
Note:
The XMLNode instances that are referring to the part of the subtree that has been deleted CANNOT be used anymore!!. Unexpected results will occur if you continue using them.
Definition at line 2071 of file xmlParser.cpp.
References XMLNode::detachFromParent(), and XMLNode::emptyTheNode().
void XMLNode::deleteText (XMLCSTR lpszValue) [inherited]
Delete the text content "lpszValue" inside the current XMLNode (direct "pointer-to-pointer" comparison is used to find the right text).
Definition at line 2281 of file xmlParser.cpp.
References XMLNode::deleteText(), and XMLNode::indexText().
void XMLNode::deleteText (int i = 0) [inherited]
Delete the Ith text content of the current XMLNode.
Definition at line 2271 of file xmlParser.cpp.
References eNodeText, XMLNode::removeOrderElement(), and XMLCSTR.
Referenced by XMLNode::deleteText().