3DSlam: Updating Nodes
Updating Nodes
[Create or Update the XMLNode structure]
Functions
XMLCSTR XMLNode::updateName (XMLCSTR lpszName)
change node's name
XMLAttribute * XMLNode::updateAttribute (XMLAttribute *newAttribute, XMLAttribute *oldAttribute)
if the attribute to update is missing, a new one will be added
XMLAttribute * XMLNode::updateAttribute (XMLCSTR lpszNewValue, XMLCSTR lpszNewName=NULL, int i=0)
if the attribute to update is missing, a new one will be added
XMLAttribute * XMLNode::updateAttribute (XMLCSTR lpszNewValue, XMLCSTR lpszNewName, XMLCSTR lpszOldName)
set lpszNewName=NULL if you don't want to change the name of the attribute if the attribute to update is missing, a new one will be added
XMLCSTR XMLNode::updateText (XMLCSTR lpszNewValue, int i=0)
if the text to update is missing, a new one will be added
XMLCSTR XMLNode::updateText (XMLCSTR lpszNewValue, XMLCSTR lpszOldValue)
if the text to update is missing, a new one will be added
XMLClear * XMLNode::updateClear (XMLCSTR lpszNewContent, int i=0)
if the clearTag to update is missing, a new one will be added
XMLClear * XMLNode::updateClear (XMLClear *newP, XMLClear *oldP)
if the clearTag to update is missing, a new one will be added
XMLClear * XMLNode::updateClear (XMLCSTR lpszNewValue, XMLCSTR lpszOldValue)
if the clearTag to update is missing, a new one will be added
Detailed Description
Some update functions:
Function Documentation
XMLAttribute * XMLNode::updateAttribute (XMLCSTR lpszNewValue, XMLCSTR lpszNewName, XMLCSTR lpszOldName) [inherited]
set lpszNewName=NULL if you don't want to change the name of the attribute if the attribute to update is missing, a new one will be added
Definition at line 2548 of file xmlParser.cpp.
References stringDup(), and XMLNode::updateAttribute_WOSD().
XMLAttribute * XMLNode::updateAttribute (XMLCSTR lpszNewValue, XMLCSTR lpszNewName = NULL, int i = 0) [inherited]
if the attribute to update is missing, a new one will be added
Definition at line 2546 of file xmlParser.cpp.
References stringDup(), and XMLNode::updateAttribute_WOSD().
XMLAttribute * XMLNode::updateAttribute (XMLAttribute * newAttribute, XMLAttribute * oldAttribute) [inherited]
if the attribute to update is missing, a new one will be added
Definition at line 2544 of file xmlParser.cpp.
References XMLAttribute::lpszName, XMLAttribute::lpszValue, stringDup(), and XMLNode::updateAttribute_WOSD().
XMLClear * XMLNode::updateClear (XMLCSTR lpszNewValue, XMLCSTR lpszOldValue) [inherited]
if the clearTag to update is missing, a new one will be added
Definition at line 2556 of file xmlParser.cpp.
References stringDup(), and XMLNode::updateClear_WOSD().
XMLClear * XMLNode::updateClear (XMLClear * newP, XMLClear * oldP) [inherited]
if the clearTag to update is missing, a new one will be added
Definition at line 2558 of file xmlParser.cpp.
References XMLClear::lpszValue, stringDup(), and XMLNode::updateClear_WOSD().
XMLClear * XMLNode::updateClear (XMLCSTR lpszNewContent, int i = 0) [inherited]
if the clearTag to update is missing, a new one will be added
Definition at line 2554 of file xmlParser.cpp.
References stringDup(), and XMLNode::updateClear_WOSD().
XMLCSTR XMLNode::updateName (XMLCSTR lpszName) [inherited]
change node's name
Definition at line 2542 of file xmlParser.cpp.
References stringDup(), and XMLNode::updateName_WOSD().
XMLCSTR XMLNode::updateText (XMLCSTR lpszNewValue, XMLCSTR lpszOldValue) [inherited]
if the text to update is missing, a new one will be added
Definition at line 2552 of file xmlParser.cpp.
References stringDup(), and XMLNode::updateText_WOSD().
XMLCSTR XMLNode::updateText (XMLCSTR lpszNewValue, int i = 0) [inherited]
if the text to update is missing, a new one will be added
Definition at line 2550 of file xmlParser.cpp.
References stringDup(), and XMLNode::updateText_WOSD().