3DSlam: D:/SLAM/Programas/slamsvn/test1/main.cpp File Reference
D:/SLAM/Programas/slamsvn/test1/main.cpp File Reference
#include <stdio.h>
#include <iostream>
#include <fstream>
#include "../src/datacam.h"
#include "../src/modelcam.h"
#include "../src/map.h"
#include "../src/kalman.h"
#include "../src/updater.h"
#include "../src/tracker_surf.h"
#include "../src/freecam.h"
#include "highgui.h"
Functions
void trasf_cov ()
void conect ()
void param_init ()
void init_ptos ()
void data_out ()
int main (int argc, char **argv)
void transf_cov ()
Variables
CDataCam mDataCam
CModelCam mModelCam
CMap mMap
CKalman mKalman
CUpdater mUpdater
CTracker_surf mTracker
CFreeCam mFreeCam
ofstream outfile
ofstream plotr
int ptox [1000][120]
int ptoy [1000][120]
CvFont font
double hScale = 0.5
double vScale = 0.5
int lineWidth = 2
char strID [10]
char c
IplImage * frame = 0
IplImage * framecopy = 0
int iter
Function Documentation
void conect ()
Definition at line 41 of file main.cpp.
References CUpdater::setDataCam(), CEstimator::setDataCam(), CModelCam::setDataCam(), CUpdater::setMap(), CEstimator::setMap(), CModelCam::setMap(), CKalman::setModel(), CUpdater::setModelCam(), and CEstimator::setModelCam().
Referenced by main().
void data_out ()
Definition at line 181 of file main.cpp.
References CMap::bbdd, font, framecopy, iter, outfile, CKalman::pKalman, plotr, CDataCam::rotation, st_empty, strID, transf_cov(), and CDataCam::translation.
Referenced by main().
void init_ptos ()
PRIMERA FASE SIMULACIÓN DE LA CAMARA
Definition at line 101 of file main.cpp.
References CMap::add3D(), CMap::bbdd, CMap::ID, CMap::inited, CKalman::initState(), CModelCam::ProjectPoints(), ptox, ptoy, CDataCam::SetRotation(), CDataCam::SetTranslation(), and CMap::visible.
Referenced by main().
int main (int argc, char ** argv)
test 1
FIN ///////////////////////////////
Definition at line 363 of file main.cpp.
References CMap::bbdd, c, conect(), CKalman::Correct(), data_out(), font, framecopy, hScale, CElempunto::ID, init_ptos(), iter, lineWidth, CElempunto::old_pto, outfile, param_init(), CElempunto::phi, plotr, CKalman::Predict(), CElempunto::pto, ptox, ptoy, CUpdater::remove(), CElempunto::rho, st_empty, st_no_view, CElempunto::state, CElempunto::theta, CUpdater::update(), CKalman::UpdateMatrixSize(), CMap::visible, vScale, CElempunto::wx, CElempunto::wx_s, CElempunto::wy, CElempunto::wy_s, CElempunto::wz, and CElempunto::wz_s.
void param_init ()
Definition at line 56 of file main.cpp.
References CDataCam::distortion, CDataCam::frame_height, CDataCam::frame_width, CDataCam::SetCx(), CDataCam::SetCy(), CTracker::setDataCam(), CDataCam::SetFx(), CDataCam::SetFy(), CTracker::setMap(), CDataCam::SetRotation(), and CDataCam::SetTranslation().
Referenced by main().
void transf_cov ()
Definition at line 493 of file main.cpp.
Referenced by data_out().
void trasf_cov ()
Variable Documentation
char c
Definition at line 34 of file main.cpp.
Referenced by CSurf::find_features(), CSurf::gaussian(), main(), and CDataOut::Particle().
CvFont font
Definition at line 29 of file main.cpp.
Referenced by data_out(), and main().
IplImage* frame = 0
Definition at line 36 of file main.cpp.
Referenced by data_out(), init_ptos(), init_video(), and main().
IplImage* framecopy = 0
Definition at line 37 of file main.cpp.
Referenced by data_out(), init_ptos(), init_video(), and main().
double hScale = 0.5
Definition at line 30 of file main.cpp.
Referenced by main().
int iter
Definition at line 39 of file main.cpp.
Referenced by data_out(), init_ptos(), init_video(), and main().
int lineWidth = 2
Definition at line 32 of file main.cpp.
Referenced by main().
CDataCam mDataCam
Definition at line 16 of file main.cpp.
CFreeCam mFreeCam
Definition at line 22 of file main.cpp.
CKalman mKalman
Definition at line 19 of file main.cpp.
CMap mMap
Definition at line 18 of file main.cpp.
CModelCam mModelCam
Definition at line 17 of file main.cpp.
CTracker_surf mTracker
Definition at line 21 of file main.cpp.
CUpdater mUpdater
Definition at line 20 of file main.cpp.
ofstream outfile
Definition at line 24 of file main.cpp.
Referenced by data_out(), and main().
ofstream plotr
Definition at line 25 of file main.cpp.
Referenced by data_out(), and main().
int ptox[1000][120]
Definition at line 26 of file main.cpp.
Referenced by init_ptos(), and main().
int ptoy[1000][120]
Definition at line 27 of file main.cpp.
Referenced by init_ptos(), and main().
char strID[10]
Definition at line 33 of file main.cpp.
Referenced by data_out().
double vScale = 0.5
Definition at line 31 of file main.cpp.
Referenced by main().