3DSlam: XMLNode Struct Reference
XMLNode Struct Reference
Main Class representing a XML node.
#include <xmlParser.h>
Public Types
enum XMLCharEncoding { encoding_UTF8 = 1, encoding_ascii = 2, encoding_ShiftJIS = 3 }
Enumeration for XML character encoding.
typedef enum
XMLNode::XMLCharEncoding XMLCharEncoding
Enumeration for XML character encoding.
Public Member Functions
XMLSTR createXMLString (int nFormat=1, int *pnSize=NULL) const
Create an XML string starting from the current XMLNode.
XMLError writeToFile (XMLCSTR filename, const char *encoding=NULL, char nFormat=1) const
Save the content of an xmlNode inside a file.
XMLCSTR getName () const
name of the node
XMLCSTR getText (int i=0) const
return ith text field
int nText () const
nbr of text field
XMLNode getParentNode () const
return the parent node
XMLNode getChildNode (int i=0) const
return ith child node
XMLNode getChildNode (XMLCSTR name, int i) const
return ith child node with specific name (return an empty node if failing). If i==-1, this returns the last XMLNode with the given name.
XMLNode getChildNode (XMLCSTR name, int *i=NULL) const
return next child node with specific name (return an empty node if failing)
XMLNode getChildNodeWithAttribute (XMLCSTR tagName, XMLCSTR attributeName, XMLCSTR attributeValue=NULL, int *i=NULL) const
return child node with specific name/attribute (return an empty node if failing)
int nChildNode (XMLCSTR name) const
return the number of child node with specific name
int nChildNode () const
nbr of child node
XMLAttribute getAttribute (int i=0) const
return ith attribute
XMLCSTR getAttributeName (int i=0) const
return ith attribute name
XMLCSTR getAttributeValue (int i=0) const
return ith attribute value
char isAttributeSet (XMLCSTR name) const
test if an attribute with a specific name is given
XMLCSTR getAttribute (XMLCSTR name, int i) const
return ith attribute content with specific name (return a NULL if failing)
XMLCSTR getAttribute (XMLCSTR name, int *i=NULL) const
return next attribute content with specific name (return a NULL if failing)
int nAttribute () const
nbr of attribute
XMLClear getClear (int i=0) const
return ith clear field (comments)
int nClear () const
nbr of clear field
XMLNodeContents enumContents (XMLElementPosition i) const
enumerate all the different contents (attribute,child,text, clear) of the current XMLNode. The order is reflecting the order of the original file/string. NOTE: 0 <= i < nElement();
int nElement () const
nbr of different contents for current node
char isEmpty () const
is this node Empty?
char isDeclaration () const
is this node a declaration <? .... ?>
XMLNode deepCopy () const
deep copy (duplicate/clone) a XMLNode
~XMLNode ()
XMLNode (const XMLNode &A)
to allow shallow/fast copy:
XMLNode & operator= (const XMLNode &A)
to allow shallow/fast copy:
XMLNode ()
XMLNode addChild (XMLCSTR lpszName, char isDeclaration=FALSE, XMLElementPosition pos=-1)
Add a new child node.
XMLNode addChild (XMLNode nodeToAdd, XMLElementPosition pos=-1)
If the "nodeToAdd" has some parents, it will be detached from it's parents before being attached to the current XMLNode.
XMLAttribute * addAttribute (XMLCSTR lpszName, XMLCSTR lpszValuev)
Add a new attribute.
XMLCSTR addText (XMLCSTR lpszValue, XMLElementPosition pos=-1)
Add a new text content.
XMLClear * addClear (XMLCSTR lpszValue, XMLCSTR lpszOpen=NULL, XMLCSTR lpszClose=NULL, XMLElementPosition pos=-1)
XMLCSTR updateName (XMLCSTR lpszName)
change node's name
XMLAttribute * updateAttribute (XMLAttribute *newAttribute, XMLAttribute *oldAttribute)
if the attribute to update is missing, a new one will be added
XMLAttribute * updateAttribute (XMLCSTR lpszNewValue, XMLCSTR lpszNewName=NULL, int i=0)
if the attribute to update is missing, a new one will be added
XMLAttribute * updateAttribute (XMLCSTR lpszNewValue, XMLCSTR lpszNewName, XMLCSTR lpszOldName)
set lpszNewName=NULL if you don't want to change the name of the attribute if the attribute to update is missing, a new one will be added
XMLCSTR updateText (XMLCSTR lpszNewValue, int i=0)
if the text to update is missing, a new one will be added
XMLCSTR updateText (XMLCSTR lpszNewValue, XMLCSTR lpszOldValue)
if the text to update is missing, a new one will be added
XMLClear * updateClear (XMLCSTR lpszNewContent, int i=0)
if the clearTag to update is missing, a new one will be added
XMLClear * updateClear (XMLClear *newP, XMLClear *oldP)
if the clearTag to update is missing, a new one will be added
XMLClear * updateClear (XMLCSTR lpszNewValue, XMLCSTR lpszOldValue)
if the clearTag to update is missing, a new one will be added
void deleteNodeContent ()
The "deleteNodeContent" function forces the deletion of the content of this XMLNode and the subtree.
void deleteAttribute (int i=0)
Delete the ith attribute of the current XMLNode.
void deleteAttribute (XMLCSTR lpszName)
Delete the attribute with the given name (the "strcmp" function is used to find the right attribute).
void deleteAttribute (XMLAttribute *anAttribute)
Delete the attribute with the name "anAttribute->lpszName" (the "strcmp" function is used to find the right attribute).
void deleteText (int i=0)
Delete the Ith text content of the current XMLNode.
void deleteText (XMLCSTR lpszValue)
Delete the text content "lpszValue" inside the current XMLNode (direct "pointer-to-pointer" comparison is used to find the right text).
void deleteClear (int i=0)
Delete the Ith clear tag inside the current XMLNode.
void deleteClear (XMLCSTR lpszValue)
Delete the clear tag "lpszValue" inside the current XMLNode (direct "pointer-to-pointer" comparison is used to find the clear tag).
void deleteClear (XMLClear *p)
Delete the clear tag "p" inside the current XMLNode (direct "pointer-to-pointer" comparison on the lpszName of the clear tag is used to find the clear tag).
XMLNode addChild_WOSD (XMLSTR lpszName, char isDeclaration=FALSE, XMLElementPosition pos=-1)
Add a new child node.
XMLAttribute * addAttribute_WOSD (XMLSTR lpszName, XMLSTR lpszValue)
Add a new attribute.
XMLCSTR addText_WOSD (XMLSTR lpszValue, XMLElementPosition pos=-1)
Add a new text content.
XMLClear * addClear_WOSD (XMLSTR lpszValue, XMLCSTR lpszOpen=NULL, XMLCSTR lpszClose=NULL, XMLElementPosition pos=-1)
Add a new clear Tag.
XMLCSTR updateName_WOSD (XMLSTR lpszName)
change node's name
XMLAttribute * updateAttribute_WOSD (XMLAttribute *newAttribute, XMLAttribute *oldAttribute)
if the attribute to update is missing, a new one will be added
XMLAttribute * updateAttribute_WOSD (XMLSTR lpszNewValue, XMLSTR lpszNewName=NULL, int i=0)
if the attribute to update is missing, a new one will be added
XMLAttribute * updateAttribute_WOSD (XMLSTR lpszNewValue, XMLSTR lpszNewName, XMLCSTR lpszOldName)
set lpszNewName=NULL if you don't want to change the name of the attribute if the attribute to update is missing, a new one will be added
XMLCSTR updateText_WOSD (XMLSTR lpszNewValue, int i=0)
if the text to update is missing, a new one will be added
XMLCSTR updateText_WOSD (XMLSTR lpszNewValue, XMLCSTR lpszOldValue)
if the text to update is missing, a new one will be added
XMLClear * updateClear_WOSD (XMLSTR lpszNewContent, int i=0)
if the clearTag to update is missing, a new one will be added
XMLClear * updateClear_WOSD (XMLClear *newP, XMLClear *oldP)
if the clearTag to update is missing, a new one will be added
XMLClear * updateClear_WOSD (XMLSTR lpszNewValue, XMLCSTR lpszOldValue)
if the clearTag to update is missing, a new one will be added
XMLElementPosition positionOfText (int i=0) const
XMLElementPosition positionOfText (XMLCSTR lpszValue) const
XMLElementPosition positionOfClear (int i=0) const
XMLElementPosition positionOfClear (XMLCSTR lpszValue) const
XMLElementPosition positionOfClear (XMLClear *a) const
XMLElementPosition positionOfChildNode (int i=0) const
XMLElementPosition positionOfChildNode (XMLNode x) const
XMLElementPosition positionOfChildNode (XMLCSTR name, int i=0) const
return the position of the ith childNode with the specified name if (name==NULL) return the position of the ith childNode
Static Public Member Functions
static XMLCSTR getVersion ()
Return the XMLParser library version number.
static XMLNode parseString (XMLCSTR lpXMLString, XMLCSTR tag=NULL, XMLResults *pResults=NULL)
Parse an XML string and return the root of a XMLNode tree representing the string.
static XMLNode parseFile (XMLCSTR filename, XMLCSTR tag=NULL, XMLResults *pResults=NULL)
Parse an XML file and return the root of a XMLNode tree representing the file.
static XMLNode openFileHelper (XMLCSTR filename, XMLCSTR tag=NULL)
Parse an XML file and return the root of a XMLNode tree representing the file. A very crude error checking is made. An attempt to guess the Char Encoding used in the file is made.
static XMLCSTR getError (XMLError error)
this gives you a user-friendly explanation of the parsing error
static XMLNode emptyNode ()
return XMLNode::emptyXMLNode;
static XMLNode createXMLTopNode (XMLCSTR lpszName, char isDeclaration=FALSE)
Create the top node of an XMLNode structure.
static XMLNode createXMLTopNode_WOSD (XMLSTR lpszName, char isDeclaration=FALSE)
Create the top node of an XMLNode structure.
static char setGlobalOptions (XMLCharEncoding characterEncoding=XMLNode::encoding_UTF8, char guessWideCharChars=1, char dropWhiteSpace=1, char removeCommentsInMiddleOfText=1)
Sets the global options for the conversions.
static XMLCharEncoding guessCharEncoding (void *buffer, int bufLen, char useXMLEncodingAttribute=1)
Guess the character encoding of the string (ascii, utf8 or shift-JIS).
Static Public Attributes
static XMLNode emptyXMLNode
static XMLClear emptyXMLClear = { NULL, NULL, NULL}
static XMLAttribute emptyXMLAttribute = { NULL, NULL}
Private Types
typedef struct
XMLNode::XMLNodeDataTag XMLNodeData
Private Member Functions
XMLNode (struct XMLNodeDataTag *pParent, XMLSTR lpszName, char isDeclaration)
Constructors are protected, so use instead one of: XMLNode::parseString, XMLNode::parseFile, XMLNode::openFileHelper, XMLNode::createXMLTopNode.
XMLNode (struct XMLNodeDataTag *p)
Constructors are protected, so use instead one of: XMLNode::parseString, XMLNode::parseFile, XMLNode::openFileHelper, XMLNode::createXMLTopNode.
char parseClearTag (void *px, void *pa)
char maybeAddTxT (void *pa, XMLCSTR tokenPStr)
int ParseXMLElement (void *pXML)
void * addToOrder (int memInc, int *_pos, int nc, void *p, int size, XMLElementType xtype)
int indexText (XMLCSTR lpszValue) const
int indexClear (XMLCSTR lpszValue) const
XMLNode addChild_priv (int, XMLSTR, char, int)
XMLAttribute * addAttribute_priv (int, XMLSTR, XMLSTR)
XMLCSTR addText_priv (int, XMLSTR, int)
XMLClear * addClear_priv (int, XMLSTR, XMLCSTR, XMLCSTR, int)
void emptyTheNode (char force)
Static Private Member Functions
static XMLElementPosition findPosition (XMLNodeData *d, int index, XMLElementType xtype)
static int CreateXMLStringR (XMLNodeData *pEntry, XMLSTR lpszMarker, int nFormat)
static int removeOrderElement (XMLNodeData *d, XMLElementType t, int index)
static void exactMemory (XMLNodeData *d)
static int detachFromParent (XMLNodeData *d)
Private Attributes
XMLNodeData * d
Classes
struct XMLNodeDataTag
Detailed Description
Main Class representing a XML node.
All operations are formed using this class.
Note:
Constructors are protected, so use instead one of these four methods to get your first instance of XMLNode:
XMLNode::parseString
XMLNode::parseFile
XMLNode::openFileHelper
XMLNode::createXMLTopNode (or XMLNode::createXMLTopNode_WOSD)
Definition at line 160 of file xmlParser.h.
Member Typedef Documentation
typedef enum XMLNode::XMLCharEncoding XMLNode::XMLCharEncoding
Enumeration for XML character encoding.
typedef struct XMLNode::XMLNodeDataTag XMLNode::XMLNodeData [private]
Member Enumeration Documentation
enum XMLNode::XMLCharEncoding
Enumeration for XML character encoding.
Enumerator:
encoding_UTF8
encoding_ascii
encoding_ShiftJIS
Definition at line 401 of file xmlParser.h.
Constructor & Destructor Documentation
XMLNode::XMLNode (struct XMLNodeDataTag * pParent, XMLSTR lpszName, char isDeclaration) [private]
Constructors are protected, so use instead one of: XMLNode::parseString, XMLNode::parseFile, XMLNode::openFileHelper, XMLNode::createXMLTopNode.
Definition at line 975 of file xmlParser.cpp.
References XMLNode::XMLNodeDataTag::pChild, and updateName_WOSD().
XMLNode::XMLNode (struct XMLNodeDataTag * p) [private]
Constructors are protected, so use instead one of: XMLNode::parseString, XMLNode::parseFile, XMLNode::openFileHelper, XMLNode::createXMLTopNode.
Definition at line 974 of file xmlParser.cpp.
References XMLNode::XMLNodeDataTag::ref_count.
XMLNode::~XMLNode ()
Definition at line 2065 of file xmlParser.cpp.
References emptyTheNode().
XMLNode::XMLNode (const XMLNode & A)
to allow shallow/fast copy:
Definition at line 2128 of file xmlParser.cpp.
References d.
XMLNode::XMLNode () [inline]
Definition at line 275 of file xmlParser.h.
Referenced by addChild_priv(), createXMLTopNode(), createXMLTopNode_WOSD(), and getParentNode().
Member Function Documentation
XMLCSTR XMLNode::getVersion () [static]
Return the XMLParser library version number.
XML.c - implementation file for basic XML parser written in ANSI C++ for portability. It works by using recursion and a node tree for breaking down the elements of an XML document.
Version:
V2.38
Author:
Frank Vanden Berghen
NOTE:
If you add "#define STRICT_PARSING", on the first line of this file the parser will see the following XML-stream: some textother text as an error. Otherwise, this tring will be equivalent to: some textother text
NOTE:
If you add "#define APPROXIMATE_PARSING" on the first line of this file the parser will see the following XML-stream: <data name="n1"> <data name="n2"> <data name="n3"> as equivalent to the following XML-stream: <data name="n1"> <data name="n2"> <data name="n3"> This can be useful for badly-formed XML-streams but prevent the use of the following XML-stream (problem is: tags at contiguous levels have the same names): <data name="n1"> <data name="n2"> <data name="n3"> </data> </data>
NOTE:
If you add "#define _XMLPARSER_NO_MESSAGEBOX_" on the first line of this file the "openFileHelper" function will always display error messages inside the console instead of inside a message-box-window. Message-box-windows are available on windows 9x/NT/2000/XP/Vista only.
Copyright (c) 2002, Frank Vanden Berghen All rights reserved. See the file "AFPL-license.txt" about the licensing terms
Definition at line 71 of file xmlParser.cpp.
References _CXML.
XMLNode & XMLNode::operator= (const XMLNode & A)
to allow shallow/fast copy:
Definition at line 2116 of file xmlParser.cpp.
References d, and emptyTheNode().
char XMLNode::parseClearTag (void * px, void * pa) [private]
Definition at line 1117 of file xmlParser.cpp.
References _CXML, addClear_priv(), XML::error, eXMLErrorUnmatchedEndClearTag, ALLXMLClearTag::lpszClose, ALLXMLClearTag::lpszOpen, XML::lpXML, MEMORYINCREASE, XML::nIndex, stringDup(), XMLCSTR, xstrlen(), and xstrstr().
Referenced by ParseXMLElement().
char XMLNode::maybeAddTxT (void * pa, XMLCSTR tokenPStr) [private]
Definition at line 1169 of file xmlParser.cpp.
References addText_priv(), deleteClear(), dropWhiteSpace, eNodeClear, eNodeText, fromXMLString(), ALLXMLClearTag::lpszOpen, XML::lpszText, MEMORYINCREASE, removeCommentsInMiddleOfText, XML_isSPACECHAR, XMLCHAR, XMLCSTR, XMLSTR, and xstrlen().
Referenced by ParseXMLElement().
int XMLNode::ParseXMLElement (void * pXML) [private]
Definition at line 1209 of file xmlParser.cpp.
References _CXML, addAttribute_priv(), addChild_priv(), XML::cbEndTag, XML::cbNewElement, eAttribEquals, eAttribName, eAttribValue, eInsideTag, emptyXMLNode, eOutsideTag, XML::error, eTokenClear, eTokenCloseTag, eTokenDeclaration, eTokenEquals, eTokenError, eTokenQuotedText, eTokenShortHandClose, eTokenTagEnd, eTokenTagStart, eTokenText, exactMemory(), eXMLErrorMissingEndTag, eXMLErrorMissingEndTagName, eXMLErrorMissingTagName, eXMLErrorUnexpectedToken, eXMLErrorUnmatchedEndTag, FALSE, fromXMLString(), GetNextToken(), isEmpty(), XML::lpEndTag, XML::lpNewElement, XML::lpszText, XML::lpXML, maybeAddTxT(), MEMORYINCREASE, myTagCompare(), XML::nFirst, XML::nIndex, XML::nIndexMissigEndTag, parseClearTag(), ParseXMLElement(), NextToken::pClr, NextToken::pStr, stringDup(), TRUE, XMLCSTR, and XMLSTR.
Referenced by parseString(), and ParseXMLElement().
void * XMLNode::addToOrder (int memInc, int * _pos, int nc, void * p, int size, XMLElementType xtype) [private]
Definition at line 1037 of file xmlParser.cpp.
References myRealloc().
Referenced by addChild(), addChild_priv(), addClear_priv(), and addText_priv().
int XMLNode::indexText (XMLCSTR lpszValue) const [private]
Definition at line 2261 of file xmlParser.cpp.
References XMLCSTR.
Referenced by deleteText(), positionOfText(), and updateText_WOSD().
int XMLNode::indexClear (XMLCSTR lpszValue) const [private]
Definition at line 2310 of file xmlParser.cpp.
Referenced by deleteClear(), positionOfClear(), and updateClear_WOSD().
XMLNode XMLNode::addChild_priv (int memoryIncrease, XMLSTR lpszName, char isDeclaration, int pos) [private]
Definition at line 1064 of file xmlParser.cpp.
References addToOrder(), emptyXMLNode, eNodeChild, and XMLNode().
Referenced by addChild(), addChild_WOSD(), and ParseXMLElement().
XMLAttribute * XMLNode::addAttribute_priv (int memoryIncrease, XMLSTR lpszName, XMLSTR lpszValuev) [private]
Definition at line 1075 of file xmlParser.cpp.
References emptyXMLAttribute, XMLAttribute::lpszName, XMLAttribute::lpszValue, myFree(), and myRealloc().
Referenced by addAttribute(), addAttribute_WOSD(), and ParseXMLElement().
XMLCSTR XMLNode::addText_priv (int memoryIncrease, XMLSTR lpszValue, int pos) [private]
Definition at line 1089 of file xmlParser.cpp.
References addToOrder(), eNodeText, myFree(), XMLCSTR, and XMLSTR.
Referenced by addText(), addText_WOSD(), and maybeAddTxT().
XMLClear * XMLNode::addClear_priv (int memoryIncrease, XMLSTR lpszValue, XMLCSTR lpszOpen, XMLCSTR lpszClose, int pos) [private]
Definition at line 1100 of file xmlParser.cpp.
References addToOrder(), emptyXMLClear, eNodeClear, ALLXMLClearTag::lpszClose, XMLClear::lpszCloseTag, ALLXMLClearTag::lpszOpen, XMLClear::lpszOpenTag, XMLClear::lpszValue, and myFree().
Referenced by addClear(), addClear_WOSD(), and parseClearTag().
void XMLNode::emptyTheNode (char force) [private]
Definition at line 2077 of file xmlParser.cpp.
References d, detachFromParent(), emptyTheNode(), XMLNode::XMLNodeDataTag::lpszName, XMLAttribute::lpszName, XMLAttribute::lpszValue, XMLClear::lpszValue, myFree(), XMLNode::XMLNodeDataTag::nAttribute, XMLNode::XMLNodeDataTag::nChild, XMLNode::XMLNodeDataTag::nClear, XMLNode::XMLNodeDataTag::nText, XMLNode::XMLNodeDataTag::pAttribute, XMLNode::XMLNodeDataTag::pChild, XMLNode::XMLNodeDataTag::pClear, XMLNode::XMLNodeDataTag::pOrder, XMLNode::XMLNodeDataTag::pParent, XMLNode::XMLNodeDataTag::pText, and XMLNode::XMLNodeDataTag::ref_count.
Referenced by deleteNodeContent(), emptyTheNode(), operator=(), and ~XMLNode().
XMLElementPosition XMLNode::findPosition (XMLNodeData * d, int index, XMLElementType xtype) [inline, static, private]
Definition at line 1016 of file xmlParser.cpp.
References XMLNode::XMLNodeDataTag::pOrder.
Referenced by positionOfChildNode(), positionOfClear(), positionOfText(), and removeOrderElement().
int XMLNode::CreateXMLStringR (XMLNodeData * pEntry, XMLSTR lpszMarker, int nFormat) [static, private]
Definition at line 1771 of file xmlParser.cpp.
References _CXML, charmemset(), d, eNodeChild, eNodeClear, eNodeText, INDENTCHAR, XMLNode::XMLNodeDataTag::isDeclaration, ToXMLStringTool::lengthXMLString(), LENSTR, XMLClear::lpszCloseTag, XMLAttribute::lpszName, XMLNode::XMLNodeDataTag::lpszName, XMLClear::lpszOpenTag, XMLClear::lpszValue, XMLAttribute::lpszValue, XMLNode::XMLNodeDataTag::nAttribute, XMLNode::XMLNodeDataTag::nChild, XMLNode::XMLNodeDataTag::nClear, XMLNode::XMLNodeDataTag::nText, XMLNode::XMLNodeDataTag::pAttribute, XMLNode::XMLNodeDataTag::pChild, XMLNode::XMLNodeDataTag::pClear, XMLNode::XMLNodeDataTag::pOrder, XMLNode::XMLNodeDataTag::pText, ToXMLStringTool::toXMLUnSafe(), XMLCSTR, and xstrcpy().
Referenced by createXMLString().
int XMLNode::removeOrderElement (XMLNodeData * d, XMLElementType t, int index) [static, private]
Definition at line 1024 of file xmlParser.cpp.
References findPosition(), XMLNode::XMLNodeDataTag::nChild, XMLNode::XMLNodeDataTag::nClear, XMLNode::XMLNodeDataTag::nText, and XMLNode::XMLNodeDataTag::pOrder.
Referenced by deleteClear(), deleteText(), and detachFromParent().
void XMLNode::exactMemory (XMLNodeData * d) [static, private]
Definition at line 1160 of file xmlParser.cpp.
References XMLNode::XMLNodeDataTag::nAttribute, XMLNode::XMLNodeDataTag::nChild, XMLNode::XMLNodeDataTag::nClear, XMLNode::XMLNodeDataTag::nText, XMLNode::XMLNodeDataTag::pAttribute, XMLNode::XMLNodeDataTag::pChild, XMLNode::XMLNodeDataTag::pClear, XMLNode::XMLNodeDataTag::pOrder, XMLNode::XMLNodeDataTag::pText, XMLCSTR, and XMLSTR.
Referenced by ParseXMLElement().
int XMLNode::detachFromParent (XMLNodeData * d) [static, private]
Definition at line 2054 of file xmlParser.cpp.
References eNodeChild, XMLNode::XMLNodeDataTag::pChild, XMLNode::XMLNodeDataTag::pParent, and removeOrderElement().
Referenced by addChild(), deleteNodeContent(), and emptyTheNode().
Member Data Documentation
XMLNode XMLNode::emptyXMLNode [static]
Definition at line 275 of file xmlParser.h.
Referenced by addChild_priv(), getChildNode(), getChildNodeWithAttribute(), getParentNode(), parseFile(), parseString(), and ParseXMLElement().
XMLClear XMLNode::emptyXMLClear = { NULL, NULL, NULL} [static]
Definition at line 277 of file xmlParser.h.
Referenced by addClear_priv(), and getClear().
XMLAttribute XMLNode::emptyXMLAttribute = { NULL, NULL} [static]
Definition at line 278 of file xmlParser.h.
Referenced by addAttribute_priv(), and getAttribute().
XMLNodeData* XMLNode::d [private]
Definition at line 498 of file xmlParser.h.
Referenced by addChild(), CreateXMLStringR(), deepCopy(), emptyTheNode(), getChildNode(), nChildNode(), operator=(), positionOfChildNode(), and XMLNode().
The documentation for this struct was generated from the following files:
D:/SLAM/Programas/slamsvn/src/xmlParser.h
D:/SLAM/Programas/slamsvn/src/xmlParser.cpp