3DSlam: XMLParserBase64Tool Struct Reference
XMLParserBase64Tool Struct Reference
[Helper class to include binary data inside XML strings using "Base64 encoding".]
Helper class to include binary data inside XML strings using "Base64 encoding".
#include <xmlParser.h>
Public Member Functions
XMLParserBase64Tool ()
~XMLParserBase64Tool ()
void freeBuffer ()
Call this function when you have finished using this object to release memory used by the internal buffer.
XMLSTR encode (unsigned char *inByteBuf, unsigned int inByteLen, char formatted=0)
returns a pointer to an internal buffer containing the base64 string containing the binary data encoded from "inByteBuf"
unsigned char * decode (XMLCSTR inString, int *outByteLen=NULL, XMLError *xe=NULL)
returns a pointer to an internal buffer containing the binary data decoded from "inString"
Static Public Member Functions
static int encodeLength (int inBufLen, char formatted=0)
return the length of the base64 string that encodes a data buffer of size inBufLen bytes.
static unsigned int decodeSize (XMLCSTR inString, XMLError *xe=NULL)
returns the number of bytes which will be decoded from "inString".
static unsigned char decode (XMLCSTR inString, unsigned char *outByteBuf, int inMaxByteOutBuflen, XMLError *xe=NULL)
deprecated.
Private Member Functions
void alloc (int newsize)
Private Attributes
void * buf
int buflen
Detailed Description
Helper class to include binary data inside XML strings using "Base64 encoding".
The "XMLParserBase64Tool" class allows you to include any binary data (images, sounds,...) into an XML document using "Base64 encoding". This class is completely separated from the rest of the xmlParser library and can be removed without any problem. To include some binary data into an XML file, you must convert the binary data into standard text (using "encode"). To retrieve the original binary data from the b64-encoded text included inside the XML file, use "decode". Alternatively, these functions can also be used to "encrypt/decrypt" some critical data contained inside the XML (it's not a strong encryption at all, but sometimes it can be useful).
Definition at line 599 of file xmlParser.h.
Constructor & Destructor Documentation
XMLParserBase64Tool::XMLParserBase64Tool () [inline]
Definition at line 602 of file xmlParser.h.
XMLParserBase64Tool::~XMLParserBase64Tool ()
Definition at line 2653 of file xmlParser.cpp.
References freeBuffer().
Member Function Documentation
void XMLParserBase64Tool::freeBuffer ()
Call this function when you have finished using this object to release memory used by the internal buffer.
Definition at line 2655 of file xmlParser.cpp.
References buf, and buflen.
Referenced by ~XMLParserBase64Tool().
int XMLParserBase64Tool::encodeLength (int inBufLen, char formatted = 0) [static]
return the length of the base64 string that encodes a data buffer of size inBufLen bytes.
Parameters:
formatted If "formatted"=true, some space will be reserved for a carriage-return every 72 chars.
Definition at line 2657 of file xmlParser.cpp.
Referenced by encode().
XMLSTR XMLParserBase64Tool::encode (unsigned char * inByteBuf, unsigned int inByteLen, char formatted = 0)
returns a pointer to an internal buffer containing the base64 string containing the binary data encoded from "inByteBuf"
The "base64Encode" function returns a string containing the base64 encoding of "inByteLen" bytes from "inByteBuf". If "formatted" parameter is true, then there will be a carriage-return every 72 chars. The string will be free'd when the XMLParserBase64Tool object is deleted. All returned strings are sharing the same memory space.
Definition at line 2664 of file xmlParser.cpp.
References _CXML, alloc(), buf, encodeLength(), XMLCHAR, and XMLSTR.
unsigned int XMLParserBase64Tool::decodeSize (XMLCSTR inString, XMLError * xe = NULL) [static]
returns the number of bytes which will be decoded from "inString".
Definition at line 2699 of file xmlParser.cpp.
References eXMLErrorBase64DataSizeIsNotMultipleOf4, eXMLErrorBase64DecodeIllegalCharacter, and eXMLErrorNone.
Referenced by decode().
unsigned char * XMLParserBase64Tool::decode (XMLCSTR inString, int * outByteLen = NULL, XMLError * xe = NULL)
returns a pointer to an internal buffer containing the binary data decoded from "inString"
The "decode" function returns a pointer to a buffer containing the binary data decoded from "inString" The output buffer will be free'd when the XMLParserBase64Tool object is deleted. All output buffer are sharing the same memory space.
Parameters:
inString If "instring" is malformed, NULL will be returned
Definition at line 2787 of file xmlParser.cpp.
References alloc(), buf, decodeSize(), and eXMLErrorNone.
unsigned char XMLParserBase64Tool::decode (XMLCSTR inString, unsigned char * outByteBuf, int inMaxByteOutBuflen, XMLError * xe = NULL) [static]
deprecated.
decodes data from "inString" to "outByteBuf". You need to provide the size (in byte) of "outByteBuf" in "inMaxByteOutBuflen". If "outByteBuf" is not large enough or if data is malformed, then "FALSE" will be returned; otherwise "TRUE".
Definition at line 2721 of file xmlParser.cpp.
References BASE64DECODE_READ_NEXT_CHAR, eXMLErrorBase64DecodeBufferTooSmall, eXMLErrorBase64DecodeTruncatedData, and eXMLErrorNone.
void XMLParserBase64Tool::alloc (int newsize) [private]
Definition at line 2781 of file xmlParser.cpp.
References buf, and buflen.
Referenced by decode(), and encode().
Member Data Documentation
void* XMLParserBase64Tool::buf [private]
Definition at line 634 of file xmlParser.h.
Referenced by alloc(), decode(), encode(), and freeBuffer().
int XMLParserBase64Tool::buflen [private]
Definition at line 635 of file xmlParser.h.
Referenced by alloc(), and freeBuffer().
The documentation for this struct was generated from the following files:
D:/SLAM/Programas/slamsvn/src/xmlParser.h
D:/SLAM/Programas/slamsvn/src/xmlParser.cpp