3DSlam: ToXMLStringTool Struct Reference
ToXMLStringTool Struct Reference
[Helper class to create XML files using "printf", "fprintf", "cout",... functions.]
Helper class to create XML files using "printf", "fprintf", "cout",... functions.
#include <xmlParser.h>
Public Member Functions
ToXMLStringTool ()
~ToXMLStringTool ()
void freeBuffer ()
call this function when you have finished using this object to release memory used by the internal buffer.
XMLSTR toXML (XMLCSTR source)
returns a pointer to an internal buffer that contains a XML-encoded string based on the "source" parameter.
Static Public Member Functions
static XMLSTR toXMLUnSafe (XMLSTR dest, XMLCSTR source)
deprecated: use "toXML" instead
static int lengthXMLString (XMLCSTR source)
deprecated: use "toXML" instead
Private Attributes
XMLSTR buf
int buflen
Detailed Description
Helper class to create XML files using "printf", "fprintf", "cout",... functions.
The ToXMLStringTool class helps you creating XML files using "printf", "fprintf", "cout",... functions. The "ToXMLStringTool" class is processing strings so that all the characters &,",',<,> are replaced by their XML equivalent:
&amp;, &quot;, &apos;, &lt;, &gt;
Using the "ToXMLStringTool class" and the "fprintf function" is THE most efficient way to produce VERY large XML documents VERY fast.
Note:
If you are creating from scratch an XML file using the provided XMLNode class you must not use the "ToXMLStringTool" class (because the "XMLNode" class does the processing job for you during rendering).
Definition at line 567 of file xmlParser.h.
Constructor & Destructor Documentation
ToXMLStringTool::ToXMLStringTool () [inline]
Definition at line 570 of file xmlParser.h.
ToXMLStringTool::~ToXMLStringTool ()
Definition at line 640 of file xmlParser.cpp.
References freeBuffer().
Member Function Documentation
void ToXMLStringTool::freeBuffer ()
call this function when you have finished using this object to release memory used by the internal buffer.
Definition at line 641 of file xmlParser.cpp.
References buf, and buflen.
Referenced by ~ToXMLStringTool().
XMLSTR ToXMLStringTool::toXML (XMLCSTR source)
returns a pointer to an internal buffer that contains a XML-encoded string based on the "source" parameter.
Definition at line 642 of file xmlParser.cpp.
References buf, buflen, lengthXMLString(), toXMLUnSafe(), XMLCHAR, and XMLSTR.
XMLSTR ToXMLStringTool::toXMLUnSafe (XMLSTR dest, XMLCSTR source) [static]
deprecated: use "toXML" instead
The "toXMLUnSafe" function is deprecated because there is a possibility of "destination-buffer-overflow". It converts the string "source" to the string "dest".
Definition at line 584 of file xmlParser.cpp.
References XMLCharacterEntity::c, XMLCharacterEntity::l, XMLCharacterEntity::s, XMLCHAR, XMLSTR, and xstrcpy().
Referenced by XMLNode::CreateXMLStringR(), and toXML().
int ToXMLStringTool::lengthXMLString (XMLCSTR source) [static]
deprecated: use "toXML" instead
Definition at line 616 of file xmlParser.cpp.
References XMLCharacterEntity::c, XMLCharacterEntity::l, XMLCharacterEntity::s, and XMLCHAR.
Referenced by XMLNode::CreateXMLStringR(), and toXML().
Member Data Documentation
XMLSTR ToXMLStringTool::buf [private]
Definition at line 583 of file xmlParser.h.
Referenced by freeBuffer(), and toXML().
int ToXMLStringTool::buflen [private]
Definition at line 584 of file xmlParser.h.
Referenced by freeBuffer(), and toXML().
The documentation for this struct was generated from the following files:
D:/SLAM/Programas/slamsvn/src/xmlParser.h
D:/SLAM/Programas/slamsvn/src/xmlParser.cpp