3DSlam: D:/SLAM/Programas/slamsvn/test1/test2.cpp File Reference
D:/SLAM/Programas/slamsvn/test1/test2.cpp File Reference
#include <stdio.h>
#include <iostream>
#include <fstream>
#include <cstdlib>
#include <jni.h>
#include <time.h>
#include "../src/datacam.h"
#include "../src/modelcam.h"
#include "../src/map.h"
#include "../src/kalman.h"
#include "../src/updater.h"
#include "../src/tracker_surf.h"
#include "../src/tracker_harris.h"
#include "../src/freecam.h"
#include "../src/dataout.h"
#include "highgui.h"
#include "../src/particlefilter.h"
#include "../src/trackerfile.h"
#include "../src/xmlParser.h"
Defines
#define RHO_INIT_DIST 1
#define DATA "/media/WOXTER/SLAM/Datos/heli/kkk%0.4d.tif"
#define LINUX
#define KALMAN
Functions
float randomVector (float max, float min)
JNIEnv * create_vm ()
void invoke_class ()
void conect ()
void param_init ()
void init_video (int argc, char **argv)
void init_ptos ()
void data_out ()
int main (int argc, char **argv)
Variables
CDataCam mDataCam
CModelCam mModelCam
CMap mMap
CUpdater mUpdater
CTracker * pTracker
CFreeCam mVehicle
CKalman mEstimator
CDataOut mDataOut
XMLNode xMainNode
int ptox [1000][120]
int ptoy [1000][120]
CvCapture * capture = 0
video variables
bool video = true
define si se usa un origen de video o de seq. de imagenes
char c
IplImage * frame = 0
IplImage * frameold = 0
IplImage * framecopy = 0
FILE * gplot = 0
int iter = 1
variable para contar la iteracion;
jobject startobj
objeto start
jmethodID startcons
jmethodID openMethod
jmethodID setImage
variable clase start
JNIEnv * env
Define Documentation
#define DATA "/media/WOXTER/SLAM/Datos/heli/kkk%0.4d.tif"
Definition at line 29 of file test2.cpp.
Referenced by init_ptos(), init_video(), and main().
#define KALMAN
Definition at line 40 of file test2.cpp.
#define LINUX
Definition at line 32 of file test2.cpp.
#define RHO_INIT_DIST 1
Definition at line 24 of file test2.cpp.
Referenced by init_ptos().
Function Documentation
void conect ()
Definition at line 179 of file test2.cpp.
References CTracker::setDataCam(), CDataOut::setDataCam(), CUpdater::setDataCam(), CEstimator::setDataCam(), CModelCam::setDataCam(), CDataOut::setKalman(), CDataOut::setMap(), CUpdater::setMap(), CEstimator::setMap(), CModelCam::setMap(), CKalman::setModel(), CDataOut::setModelCam(), CUpdater::setModelCam(), CEstimator::setModelCam(), CDataOut::setParticle(), CDataOut::setTracker(), and CUpdater::setTracker().
JNIEnv* create_vm ()
Definition at line 85 of file test2.cpp.
References env.
Referenced by main().
void data_out ()
Definition at line 355 of file test2.cpp.
References CDataOut::Cam(), CDataOut::Disp_out(), CDataOut::Draw(), CDataOut::Feat(), CDataOut::Frame(), frame, framecopy, gplot, CDataOut::iter, iter, and CDataOut::Particle().
void init_ptos ()
Definition at line 315 of file test2.cpp.
References CUpdater::Add(), CMap::bbdd, capture, CModelCam::cvInverseParam(), DATA, frame, framecopy, frameold, CMap::inited, CKalman::initState(), iter, RHO_INIT_DIST, st_inited, CDataCam::translation, video, and CMap::visible.
void init_video (int argc, char ** argv)
Definition at line 276 of file test2.cpp.
References capture, DATA, frame, framecopy, frameold, iter, and video.
Referenced by main().
void invoke_class ()
Definition at line 106 of file test2.cpp.
References env, openMethod, setImage, startcons, and startobj.
Referenced by main().
int main (int argc, char ** argv)
FIN ///////////////////////////////
Definition at line 385 of file test2.cpp.
References CUpdater::Add(), c, capture, conect(), CKalman::Correct(), create_vm(), DATA, data_out(), env, frame, frameold, XMLNode::getChildNode(), XMLNode::getText(), init_ptos(), init_video(), invoke_class(), iter, CTracker::Match(), XMLNode::openFileHelper(), param_init(), CKalman::Predict(), CKalman::Print(), CModelCam::ProjectPoints(), CUpdater::remove(), setImage, startobj, CUpdater::update(), CKalman::UpdateMatrixSize(), and video.
void param_init ()
Cámaras sony?
Camara firewire escuela
Camara Genérica
Definition at line 209 of file test2.cpp.
References CDataCam::distortion, CDataCam::frame_height, CDataCam::frame_width, CModel::getMeasurementNum(), CFreeCam::getMeasurementVector(), CDataCam::SetCx(), CDataCam::SetCy(), CTracker::setDataCam(), CDataCam::SetFx(), CDataCam::SetFy(), CTracker::setMap(), CDataCam::SetRotation(), and CDataCam::SetTranslation().
float randomVector (float max, float min)
Variable Documentation
char c
Definition at line 67 of file test2.cpp.
CvCapture* capture = 0
video variables
Definition at line 65 of file test2.cpp.
Referenced by init_ptos(), init_video(), and main().
JNIEnv* env
Definition at line 82 of file test2.cpp.
Referenced by create_vm(), invoke_class(), and main().
IplImage* frame = 0
Definition at line 69 of file test2.cpp.
IplImage* framecopy = 0
Definition at line 71 of file test2.cpp.
IplImage* frameold = 0
Definition at line 70 of file test2.cpp.
Referenced by init_ptos(), init_video(), and main().
FILE* gplot = 0
Definition at line 73 of file test2.cpp.
Referenced by data_out().
int iter = 1
variable para contar la iteracion;
Definition at line 76 of file test2.cpp.
CDataCam mDataCam
Definition at line 44 of file test2.cpp.
CDataOut mDataOut
Definition at line 57 of file test2.cpp.
CKalman mEstimator
Definition at line 55 of file test2.cpp.
CMap mMap
Definition at line 46 of file test2.cpp.
CModelCam mModelCam
Definition at line 45 of file test2.cpp.
CUpdater mUpdater
Definition at line 47 of file test2.cpp.
CFreeCam mVehicle
Definition at line 51 of file test2.cpp.
jmethodID openMethod
Definition at line 81 of file test2.cpp.
Referenced by invoke_class().
int ptox[1000][120]
Definition at line 61 of file test2.cpp.
int ptoy[1000][120]
Definition at line 62 of file test2.cpp.
CTracker* pTracker
Definition at line 50 of file test2.cpp.
jmethodID setImage
variable clase start
Definition at line 81 of file test2.cpp.
Referenced by invoke_class(), and main().
jmethodID startcons
Definition at line 81 of file test2.cpp.
Referenced by invoke_class().
jobject startobj
objeto start
Variables interfaz grafica java
Definition at line 80 of file test2.cpp.
Referenced by invoke_class(), and main().
bool video = true
define si se usa un origen de video o de seq. de imagenes
Definition at line 66 of file test2.cpp.
Referenced by init_ptos(), init_video(), and main().
XMLNode xMainNode
Definition at line 59 of file test2.cpp.