3DSlam: D:/SLAM/Programas/slamsvn/src/xmlParser.cpp File Reference
D:/SLAM/Programas/slamsvn/src/xmlParser.cpp File Reference
#include "xmlParser.h"
#include <memory.h>
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
Classes
struct ALLXMLClearTag
struct XMLCharacterEntity
struct XML
struct NextToken
Defines
#define INDENTCHAR _CXML('\t')
#define XML_isSPACECHAR(ch) ((ch==_CXML('\n'))||(ch==_CXML(' '))||(ch== _CXML('\t'))||(ch==_CXML('\r')))
#define MEMORYINCREASE 50
#define LENSTR(lpsz) (lpsz ? xstrlen(lpsz) : 0)
#define BASE64DECODE_READ_NEXT_CHAR(c)
Typedefs
typedef enum XMLTokenTypeTag XMLTokenType
Enumerations
enum XMLTokenTypeTag {
eTokenText = 0, eTokenQuotedText, eTokenTagStart, eTokenTagEnd,
eTokenCloseTag, eTokenEquals, eTokenDeclaration, eTokenShortHandClose,
eTokenClear, eTokenError
}
enum Attrib { eAttribName = 0, eAttribEquals, eAttribValue }
enum Status { eInsideTag = 0, eOutsideTag }
Functions
void freeXMLString (XMLSTR t)
to free the string allocated usign the "stringDup" function.
int mmin (const int t1, const int t2)
char myIsTextWideChar (const void *b, int len)
char * myWideCharToMultiByte (const wchar_t *s)
static FILE * xfopen (XMLCSTR filename, XMLCSTR mode)
static int xstrlen (XMLCSTR c)
static int xstrnicmp (XMLCSTR c1, XMLCSTR c2, int l)
static int xstrncmp (XMLCSTR c1, XMLCSTR c2, int l)
static int xstricmp (XMLCSTR c1, XMLCSTR c2)
static XMLSTR xstrstr (XMLCSTR c1, XMLCSTR c2)
static XMLSTR xstrcpy (XMLSTR c1, XMLCSTR c2)
static int _strnicmp (const char *c1, const char *c2, int l)
char xmltoc (XMLCSTR t, char v)
int xmltoi (XMLCSTR t, int v)
long xmltol (XMLCSTR t, long v)
double xmltof (XMLCSTR t, double v)
XMLCSTR xmltoa (XMLCSTR t, XMLCSTR v)
XMLSTR stringDup (XMLCSTR lpszData, int cbData)
XMLSTR fromXMLString (XMLCSTR s, int lo, XML *pXML)
char myTagCompare (XMLCSTR cclose, XMLCSTR copen)
static XMLCHAR getNextChar (XML *pXML)
static NextToken GetNextToken (XML *pXML, int *pcbToken, enum XMLTokenTypeTag *pType)
static void myFree (void *p)
static void * myRealloc (void *p, int newsize, int memInc, int sizeofElem)
static void CountLinesAndColumns (XMLCSTR lpXML, int nUpto, XMLResults *pResults)
static void charmemset (XMLSTR dest, XMLCHAR c, int l)
Variables
static XMLNode::XMLCharEncoding characterEncoding = XMLNode::encoding_UTF8
static char guessWideCharChars = 1
static char dropWhiteSpace = 1
static char removeCommentsInMiddleOfText = 1
static ALLXMLClearTag XMLClearTags []
static XMLCharacterEntity XMLEntities []
static const char XML_utf8ByteTable [256]
static const char XML_asciiByteTable [256]
static const char XML_sjisByteTable [256]
static const char * XML_ByteTable = (const char *)XML_utf8ByteTable
static const char base64Fillchar = _CXML('=')
XMLCSTR base64EncodeTable = _CXML("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/")
const unsigned char base64DecodeTable []
Define Documentation
#define BASE64DECODE_READ_NEXT_CHAR (c)
Value:
do { c=base64DecodeTable[(unsigned char)data[i++]]; }while (c==97);   \
        if(c==98){ if(xe)*xe=eXMLErrorBase64DecodeIllegalCharacter; return 0; }
Referenced by XMLParserBase64Tool::decode().
#define INDENTCHAR _CXML('\t')
Definition at line 113 of file xmlParser.cpp.
Referenced by XMLNode::CreateXMLStringR().
#define LENSTR (lpsz) (lpsz ? xstrlen(lpsz) : 0)
Referenced by XMLNode::CreateXMLStringR().
#define MEMORYINCREASE 50
Definition at line 1001 of file xmlParser.cpp.
Referenced by XMLNode::maybeAddTxT(), XMLNode::parseClearTag(), and XMLNode::ParseXMLElement().
#define XML_isSPACECHAR (ch) ((ch==_CXML('\n'))||(ch==_CXML(' '))||(ch== _CXML('\t'))||(ch==_CXML('\r')))
Definition at line 766 of file xmlParser.cpp.
Referenced by GetNextToken(), XMLNode::guessCharEncoding(), XMLNode::maybeAddTxT(), and myTagCompare().
Typedef Documentation
typedef enum XMLTokenTypeTag XMLTokenType
Enumeration Type Documentation
enum Attrib
Enumerator:
eAttribName
eAttribEquals
eAttribValue
Definition at line 512 of file xmlParser.cpp.
enum Status
Enumerator:
eInsideTag
eOutsideTag
Definition at line 521 of file xmlParser.cpp.
enum XMLTokenTypeTag
Enumerator:
eTokenText
eTokenQuotedText
eTokenTagStart
eTokenTagEnd
eTokenCloseTag
eTokenEquals
eTokenDeclaration
eTokenShortHandClose
eTokenClear
eTokenError
Definition at line 477 of file xmlParser.cpp.
Function Documentation
static int _strnicmp (const char * c1, const char * c2, int l) [inline, static]
Definition at line 318 of file xmlParser.cpp.
static void charmemset (XMLSTR dest, XMLCHAR c, int l) [inline, static]
Definition at line 1764 of file xmlParser.cpp.
Referenced by XMLNode::CreateXMLStringR().
static void CountLinesAndColumns (XMLCSTR lpXML, int nUpto, XMLResults * pResults) [static]
Definition at line 1620 of file xmlParser.cpp.
References _CXML, eXMLErrorNone, getNextChar(), XMLResults::nColumn, XML::nIndex, XMLResults::nLine, TRUE, and XMLCHAR.
Referenced by XMLNode::parseString().
void freeXMLString (XMLSTR t)
to free the string allocated usign the "stringDup" function.
Definition at line 72 of file xmlParser.cpp.
XMLSTR fromXMLString (XMLCSTR s, int lo, XML * pXML)
Definition at line 650 of file xmlParser.cpp.
References _CXML, XMLCharacterEntity::c, XML::error, eXMLErrorCharacterCodeAbove255, eXMLErrorUnknownCharacterEntity, XMLCharacterEntity::l, XMLCharacterEntity::s, XMLCHAR, XMLCSTR, XMLSTR, and xstrnicmp().
Referenced by XMLNode::maybeAddTxT(), and XMLNode::ParseXMLElement().
static XMLCHAR getNextChar (XML * pXML) [inline, static]
Definition at line 787 of file xmlParser.cpp.
References XML::lpXML, XML::nIndex, and XMLCHAR.
Referenced by CountLinesAndColumns(), and GetNextToken().
static NextToken GetNextToken (XML * pXML, int * pcbToken, enum XMLTokenTypeTag * pType) [static]
Definition at line 800 of file xmlParser.cpp.
References _CXML, eTokenClear, eTokenCloseTag, eTokenDeclaration, eTokenEquals, eTokenError, eTokenQuotedText, eTokenShortHandClose, eTokenTagEnd, eTokenTagStart, eTokenText, FALSE, getNextChar(), ALLXMLClearTag::lpszOpen, XML::lpXML, XML::nIndex, ALLXMLClearTag::openTagLen, NextToken::pClr, NextToken::pStr, TRUE, XML_isSPACECHAR, XMLCHAR, and xstrncmp().
Referenced by XMLNode::ParseXMLElement().
int mmin (const int t1, const int t2) [inline]
Definition at line 77 of file xmlParser.cpp.
Referenced by XMLNode::guessCharEncoding(), and myIsTextWideChar().
static void myFree (void * p) [inline, static]
Definition at line 1003 of file xmlParser.cpp.
Referenced by XMLNode::addAttribute_priv(), XMLNode::addClear_priv(), XMLNode::addText_priv(), and XMLNode::emptyTheNode().
char myIsTextWideChar (const void * b, int len)
Definition at line 160 of file xmlParser.cpp.
References FALSE, mmin(), and TRUE.
Referenced by XMLNode::guessCharEncoding(), and XMLNode::parseFile().
static void* myRealloc (void * p, int newsize, int memInc, int sizeofElem) [inline, static]
Definition at line 1004 of file xmlParser.cpp.
Referenced by XMLNode::addAttribute_priv(), and XMLNode::addToOrder().
char myTagCompare (XMLCSTR cclose, XMLCSTR copen)
Definition at line 769 of file xmlParser.cpp.
References _CXML, XML_isSPACECHAR, XMLCHAR, xstrlen(), and xstrnicmp().
Referenced by XMLNode::ParseXMLElement().
char* myWideCharToMultiByte (const wchar_t * s)
Definition at line 263 of file xmlParser.cpp.
Referenced by XMLNode::parseFile().
XMLSTR stringDup (XMLCSTR source, int cbData = -1)
Duplicate (copy in a new allocated buffer) the source string. This is a very handy function when used with all the "XMLNode::*_WOSD" functions (xmlModify).
Parameters:
cbData If !=0 then cbData is the number of chars to duplicate. New strings allocated with this function should be free'd using the "freeXMLString" function.
Definition at line 569 of file xmlParser.cpp.
References XMLCHAR, XMLSTR, and xstrlen().
Referenced by XMLNode::addAttribute(), XMLNode::addChild(), XMLNode::addClear(), XMLNode::addText(), XMLNode::createXMLTopNode(), XMLNode::deepCopy(), XMLNode::parseClearTag(), XMLNode::ParseXMLElement(), XMLNode::updateAttribute(), XMLNode::updateAttribute_WOSD(), XMLNode::updateClear(), XMLNode::updateName(), and XMLNode::updateText().
static FILE* xfopen (XMLCSTR filename, XMLCSTR mode) [inline, static]
Definition at line 310 of file xmlParser.cpp.
Referenced by XMLNode::openFileHelper(), XMLNode::parseFile(), and XMLNode::writeToFile().
static XMLSTR xstrcpy (XMLSTR c1, XMLCSTR c2) [inline, static]
Definition at line 316 of file xmlParser.cpp.
References XMLSTR.
Referenced by XMLNode::CreateXMLStringR(), and ToXMLStringTool::toXMLUnSafe().
static int xstricmp (XMLCSTR c1, XMLCSTR c2) [inline, static]
Definition at line 314 of file xmlParser.cpp.
Referenced by XMLNode::getAttribute(), XMLNode::getChildNode(), XMLNode::getChildNodeWithAttribute(), XMLNode::isAttributeSet(), XMLNode::nChildNode(), and XMLNode::parseString().
static int xstrlen (XMLCSTR c) [inline, static]
Definition at line 311 of file xmlParser.cpp.
Referenced by XMLNode::maybeAddTxT(), myTagCompare(), XMLNode::parseClearTag(), XMLNode::parseString(), and stringDup().
static int xstrncmp (XMLCSTR c1, XMLCSTR c2, int l) [inline, static]
Definition at line 313 of file xmlParser.cpp.
Referenced by GetNextToken().
static int xstrnicmp (XMLCSTR c1, XMLCSTR c2, int l) [inline, static]
Definition at line 312 of file xmlParser.cpp.
Referenced by fromXMLString(), XMLNode::guessCharEncoding(), and myTagCompare().
static XMLSTR xstrstr (XMLCSTR c1, XMLCSTR c2) [inline, static]
Definition at line 315 of file xmlParser.cpp.
References XMLSTR.
Referenced by XMLNode::parseClearTag().
Variable Documentation
const unsigned char base64DecodeTable[]
Initial value:
 {
    99,98,98,98,98,98,98,98,98,97,  97,98,98,97,98,98,98,98,98,98,  98,98,98,98,98,98,98,98,98,98,
    98,98,97,98,98,98,98,98,98,98,  98,98,98,62,98,98,98,63,52,53,  54,55,56,57,58,59,60,61,98,98,
    98,96,98,98,98, 0, 1, 2, 3, 4,   5, 6, 7, 8, 9,10,11,12,13,14,  15,16,17,18,19,20,21,22,23,24,
    25,98,98,98,98,98,98,26,27,28,  29,30,31,32,33,34,35,36,37,38,  39,40,41,42,43,44,45,46,47,48,
    49,50,51,98,98,98,98,98,98,98,  98,98,98,98,98,98,98,98,98,98,  98,98,98,98,98,98,98,98,98,98,
    98,98,98,98,98,98,98,98,98,98,  98,98,98,98,98,98,98,98,98,98,  98,98,98,98,98,98,98,98,98,98,
    98,98,98,98,98,98,98,98,98,98,  98,98,98,98,98,98,98,98,98,98,  98,98,98,98,98,98,98,98,98,98,
    98,98,98,98,98,98,98,98,98,98,  98,98,98,98,98,98,98,98,98,98,  98,98,98,98,98,98,98,98,98,98,
    98,98,98,98,98,98,98,98,98,98,  98,98,98,98,98,98
}
Definition at line 2641 of file xmlParser.cpp.
XMLCSTR base64EncodeTable = _CXML("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/")
Definition at line 2637 of file xmlParser.cpp.
const char base64Fillchar = _CXML('=') [static]
Definition at line 2634 of file xmlParser.cpp.
XMLNode::XMLCharEncoding characterEncoding = XMLNode::encoding_UTF8 [static]
Definition at line 74 of file xmlParser.cpp.
Referenced by XMLNode::setGlobalOptions(), and XMLNode::writeToFile().
char dropWhiteSpace = 1 [static]
Definition at line 75 of file xmlParser.cpp.
Referenced by XMLNode::createXMLString(), XMLNode::maybeAddTxT(), XMLNode::openFileHelper(), and XMLNode::setGlobalOptions().
char guessWideCharChars = 1 [static]
Definition at line 75 of file xmlParser.cpp.
Referenced by XMLNode::guessCharEncoding(), XMLNode::openFileHelper(), XMLNode::parseFile(), and XMLNode::setGlobalOptions().
char removeCommentsInMiddleOfText = 1 [static]
Definition at line 75 of file xmlParser.cpp.
Referenced by XMLNode::maybeAddTxT(), XMLNode::openFileHelper(), and XMLNode::setGlobalOptions().
const char XML_asciiByteTable[256] [static]
Initial value:
{
    0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
}
Definition at line 439 of file xmlParser.cpp.
const char* XML_ByteTable = (const char *)XML_utf8ByteTable [static]
Definition at line 468 of file xmlParser.cpp.
const char XML_sjisByteTable[256] [static]
Initial value:
{
    0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
    2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
}
Definition at line 448 of file xmlParser.cpp.
const char XML_utf8ByteTable[256] [static]
Initial value:
{
    0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
    2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
    3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
    4,4,4,4,4,1,1,1,1,1,1,1,1,1,1,1
}
Definition at line 419 of file xmlParser.cpp.
ALLXMLClearTag XMLClearTags[] [static]
Initial value:
{
    {    _CXML("<![CDATA["),9,  _CXML("]]>")      },
    {    _CXML("<!DOCTYPE"),9,  _CXML(">")        },
    {    _CXML("<!--")     ,4,  _CXML("-->")      },
    {    _CXML("<PRE>")    ,5,  _CXML("</PRE>")   },
    {    _CXML("<Script>") ,8,  _CXML("</Script>")},
    {    NULL              ,0,  NULL           }
}
Definition at line 85 of file xmlParser.cpp.
XMLCharacterEntity XMLEntities[] [static]
Initial value:
{
    { _CXML("&amp;" ), 5, _CXML('&' )},
    { _CXML("&lt;"  ), 4, _CXML('<' )},
    { _CXML("&gt;"  ), 4, _CXML('>' )},
    { _CXML("&quot;"), 6, _CXML('\"')},
    { _CXML("&apos;"), 6, _CXML('\'')},
    { NULL           , 0, '\0'    }
}
Definition at line 100 of file xmlParser.cpp.